### ISSUE TITLE
VisualStudio extension can't parse the version `0.26.1+3d5768a543259cd498064d1ff364f4c741905ab6`

### ISSUE THREAD

**Issue by bartoszluka** [belav/csharpier#1000]
When initializing `csharpier` in the VisualStudio extension, there is a `FormatException` thrown and logged.
I traced it back to the [this line](https://github.com/belav/csharpier/blob/3d5768a543259cd498064d1ff364f4c741905ab6/Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessProvider.cs#L204C17-L204C17). Since `0.26.0` versions also contain something after the numbers, which breaks the extension.

I confirmed it by running

```csharp
new System.Version("0.26.1+3d5768a543259cd498064d1ff364f4c741905ab6"); 
// FormatException: The input string '1+3d5768a543259cd498064d1ff364f4c741905ab6' was not in a correct format.
```

**Comment by bartoszluka** [comment]
Quick solution would be to discard everything after the plus when parsing the version. I can open a PR with the fix if this satisfies you

```csharp
var installedVersion = new Version(version.Split('+').First());
```

**Comment by belav** [comment]
It seems at some point (probably 0.26.0) the action I use to publish to nuget started including the commit hash on the version number. There are 3 extensions that would need to be updated so I'll just republish a version 0.26.2 without the commit hash.

It is probably worth still updating the 3 extensions just in case this happens again, and to help anyone that doesn't update to 0.26.2.

**Comment by belav** [comment]
I take that back, it isn't the action adding it. `dotnet pack` is now including the commit hash in the nuspec, and `dotnet csharpier --version` is now including the commit hash after the version number. It isn't clear how to prevent that. 

If you open a PR for VS I can get that published. And I'll take care of VSCode and Rider later today. Thanks!

**Comment by bartoszluka** [comment]
I can confirm that it solved the issue, thank you!
