### ISSUE TITLE
CSharpier doesn't respect editorconfig csharp_space_between_empty_square_brackets = false

### ISSUE THREAD

**Issue by golavr** [belav/csharpier#1002]
### Expected
```csharp
        List<int> ids = [];
        var store = await Get<List<PositionAdd>>(Key) ?? [];
```

### Actual
**First line:** extra space before square bracket and space between empty square brackets
**Second line:** space between empty square brackets
```csharp
        List<int> ids =  [ ];
        var store = await Get<List<PositionAdd>>(Key) ?? [ ];
```

**Comment by belav** [comment]
CSharpier doesn't respect any editorconfig settings beyond the basics covered [here](https://csharpier.com/docs/Configuration).

That being said, the `[ ]` was not intentional and and `[]` seems like the preferred way to format.
