### ISSUE TITLE
Global System using directives should be sorted first

### ISSUE THREAD

**Issue by vipentti** [belav/csharpier#1003]
First of all, great project and big fan of automating formatting.

I noticed an inconsistency when it comes to sorting regular `using System*` directives vs `global using System*` directives:

When sorting the regular `using` directives the System using directives are ordered before the non-system using directives.

However when sorting `global using` all the directives are grouped together and sorted as one set. 

Basically sorting the following:

```csharp
using Library;
using System;
using AnotherLibrary;
```

Results in 
```csharp
using System;
using AnotherLibrary;
using Library;
```

Where as sorting the following:

```csharp
global using Library;
global using System;
global using AnotherLibrary;
```

Results in 
```csharp
global using AnotherLibrary;
global using Library;
global using System;
```

My suggestion would be to use the same pattern with global System using directives so that they would be sorted before other non-System global using directives.

I don't mind doing the work if this sounds like a reasonable idea.

https://github.com/belav/csharpier/blob/a877f7d3b701fdd5a1a0f52a581d458897f6d570/Src/CSharpier/SyntaxPrinter/UsingDirectives.cs#L217-L223

**Comment by JamieJamesJamie** [comment]
This issue also highlights a conflict between CSharpier and [StyleCop Analyzers SA1208](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1208.md). The inconsistency mentioned is picked up by that rule.

**Comment by will-molloy** [comment]
Yeah this is inconsistent with `dotnet format style` so it conflicts with `dotnet format` (according to this page https://csharpier.com/docs/IntegratingWithLinters)
