### ISSUE TITLE
Conversion to file-scoped namespace

### ISSUE THREAD

**Issue by will-molloy** [belav/csharpier#1007]
I suggest automatic conversion to file-scoped (from block-scoped) namespaces. Not sure if it's within the scope of the project.

Expected:
```cs
namespace MyNamespace;

class MyClass { }
```

Actual:
```cs
namespace MyNamespace
{
    class MyClass { }
}
```

**Comment by belav** [comment]
In general CSharpier is only concerned with formatting via changing whitespace. There are only a couple of exceptions to that. Converting to file scoped namespaces is beyond the scope of CSharpier.
