### ISSUE TITLE
C#12 Collection expressions are prefixed with two spaces

### ISSUE THREAD

**Issue by Jackenmen** [belav/csharpier#1009]
I wanted to send some feedback about the formatting of the new collection expressions. I think it is inconsistent to prefix these with 2 spaces (I'm also not sure why such formatting was selected) when compared to how e.g. collection/object initializers are formatted:
```cs
public class Reproduction
{
    private readonly Dictionary<string, int> counts =  [ ];
    private readonly List<string> keys = { };
}
```

I'm also not sure I agree with the choice to format collection expressions with spaces between the square brackets and the elements but I suppose it's consistent with how collection/object initializers are formatted so I find it harder to argue against. It is worth noting that [MSDN formats these without spaces](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions) (while formatting collection/object initializers with spaces between the brackets) and the IDE also suggests such formatting though:
![image](https://github.com/belav/csharpier/assets/6032823/2a6a9075-6303-4e98-b216-e0f8935cb40d)

**Comment by belav** [comment]
The two spaces was unintentional, and should be an easy fix. Along with changing `[ ]` to `[]`

I don't recall if I did this intentionally. I'm gonna take another look at it. At first glance I do prefer it without the extra spaces.

Thanks for the feedback!
```c#
// input
int[] a = [1, 2, 3, 4, 5, 6, 7, 8];

// output
int[] a =  [ 1, 2, 3, 4, 5, 6, 7, 8 ];
