### ISSUE TITLE
Hangup when formatting in VSCode

### ISSUE THREAD

**Issue by hkvoch** [belav/csharpier#1014]
Hi!

First, thanks for making this amazing tool, it really saved me a lot of time :)

When using the VSCode extension, the plugin hangs up when formatting some files. After some digging, I think I found the culprit: https://github.com/belav/csharpier/blob/eb567079b7aac4b3c5c277702888edf7d3890b61/Src/CSharpier.VSCode/src/CSharpierProcessPipeMultipleFiles.ts#L29-L48
When the chunk contains multiple format results, this gets just the first one and won't call other callbacks until the next chunk arrives. An easy fix I applied locally is to wrap the "last chunk" section of the code in a while(true) loop and get all the results from the chunk. That seems to resolve the issue.

I can provide a PR for that if you want.
Cheers!

**Comment by belav** [comment]
@hkvoch I'm in here trying to fix some other issues and can include that fix as well, thanks for tracking down the fix for it!

I should have a new version out in the next day or two.
