### ISSUE TITLE
.editorconfig included .csharpierignore should be excluded

### ISSUE THREAD

**Issue by sebastieng84** [belav/csharpier#1023]
Should we exclude .editorconfig in directories that are in the .csharpierignore file? We currently have an external dependency that has a invalid key word in the .editorconfig file and it always throw an error even though that directory is ignored.

Before I actually make a PR for this, is there any reasons why we would still want to parse those files if they are included in .csharpierignore?

**Comment by sebastieng84** [comment]
.assign

**Comment by belav** [comment]
I am not looking at the code, but my guess is that the code that tries to
find all editorConfigs doesn't exclude any ignored directories.

Finding the relevant editorConfigs for each file to be formatted would be
slow unless it kept track of which paths it had already traversed and kept
the configurations in memory. Finding all of the editorConfigs upfront
seemed like it would perform about the same and be less complex to code.

In hindsight this may be causing some of the issues people are having with
IDEs. I'm hoping to start looking into the IDE problems in the next few
days.

There may be an easy fix getting the editorConfig code to exclude ignored
directories. Long term I think it makes sense to rework the editorConfig
code to keep track of what it has found and only look for new
configurations as needed.

**Comment by sebastieng84** [comment]
We can find all

**Comment by sebastieng84** [comment]
@belav I just did some tests and it's fairly simple, if you load the IgnoreFile before fetching all the .editorconfig files, you can pass it to EditorConfigParser. Then you can add `.Where(x => !ignoreFile.IsIgnored(x.FullName))`. I'll add some tests and create a PR tomorrow if I have some time so you can have a look 😄
