### ISSUE TITLE
Getting "The file did not end with a single newline" after upgrading from 0.25 to 0.26.2

### ISSUE THREAD

**Issue by loraderon** [belav/csharpier#1025]
Hi,

Many of our files are reporting "The file did not end with a single newline" when run on the CI build. I have tried 0.26 and 0.26.2 and both are failing.
The build are running on hosted agents in Azure DevOps, which are running Ubuntu and .NET 7.0.404. We have developers using both Mac and Windows and are using the CSharpier.MsBuild package.

```
Error /home/vsts/work/1/s/src/services/xxx/app/Program.cs - Was not formatted.
  The file did not end with a single newline.

##[error]/home/vsts/.nuget/packages/csharpier.msbuild/0.26.0/build/CSharpier.MsBuild.targets(19,5): Error MSB3073: The command "dotnet "/home/vsts/.nuget/packages/csharpier.msbuild/0.26.0/build/../tools/csharpier/net7.0/dotnet-csharpier.dll"  --check --no-msbuild-check "/home/vsts/work/1/s/src/services/xx/app" > /dev/null " exited with code 1.
```

![image](https://github.com/belav/csharpier/assets/76928/ae968fda-f053-4bcc-90bc-8b6095d0b642)

**Comment by belav** [comment]
Have you double checked that csharpier has formatted the `Program.cs` file? The code that ensures formatting includes a single blank line at the end of a file hasn't changed in a while.

Otherwise maybe there is some content in the file that CSharpier isn't handled correctly which is resulting in the formatting now including the blank line.

**Comment by loraderon** [comment]
Sorry for late reply. It will probably be a week or so more before I can dig deeper inteo this isse.

> Have you double checked that csharpier has formatted the Program.cs file?
Yes, they are all formatted when building locally before pushing the changes to devops.

I tried upgrading to 0.26.3, but the issue remains. 0.25.0 still works.

**Comment by Odonno** [comment]
I have the exact same problem.

-> With 0.25.0, everything worked fine.

-> With 0.26.x, it still works locally (on a Windows machine). But it shows the same EoF error on the CI (Linux machine). Can it be a mismatch in CRLF detection?

**Comment by belav** [comment]
If either of you could provide a file that causes this problem, that would help. Git can be configured to normalize line endings, clone with CRLF for windows, push with LF is fairly common, so you may have to download the file directly from git to reproduce it.

**Comment by loraderon** [comment]
I downloaded one file from devops and read all the bytes and all of them end with a single `10`  (`LF`), I see no traces of `CR`.

My local files does contain `CR` & `LF`.

I assume this has something to do with git.autocrlf

**Comment by belav** [comment]
Ah, I think I finally know what is happening. By chance do you have an `.editorconfig` with a setting for `end_of_line = crlf` ?

I found a bug in https://github.com/belav/csharpier/blob/main/Src/CSharpier/Utilities/StringDiffer.cs#L19 after staring at it for a while and suspecting something in it isn't correct. The logic for detecting line endings that differ from what csharpier expects didn't properly work when the strings being compared actually ended with line endings, so it wasn't doing much good. It only worked with line endings in the middle of strings.

`0.26.0` introduced the ability to specify line endings (re-introduced actually). It also reads configuration from an `.editorconfig` now. So if you have an editorconfig with `end_of_line` then CSharpier is expecting the file to use `\r\n`, but it is in the repo (or being cloned with) `\n`, and the bug with `StringDiffer` is reporting the problem incorrectly.

Assuming this is all true I think removing `end_of_line` from the editorconfig, or adding `endOfLine: auto` to a csharpierrc would resolve it. I'll also get the bug in `StringDiffer` fixed.

**Comment by loraderon** [comment]
Thanks for looking into it and sorry for not being able to provide more information earlier. I do have `end_of_line = crlf` and I updated to 0.26.6 but still seeing the same error, could it have anything to do with the `insert_final_newline = false`?

![image](https://github.com/belav/csharpier/assets/76928/0e748e22-fcca-4bb6-9a0e-d081e3b7e162)

**Comment by Odonno** [comment]
Ah, yes. It works for me with this configuration:

```toml
# New line preferences
end_of_line = auto
insert_final_newline = true
```

**Comment by loraderon** [comment]
> Ah, yes. It works for me with this configuration

This change works for me also 👍

**Comment by belav** [comment]
> Thanks for looking into it and sorry for not being able to provide more information earlier.

Not a problem at all, I was noodling on this for a while and didn't think to ask for what editorconfig you were using. I've since added issue templates to try to get all that info upfront.

Is there something else that is enforcing `insert_final_newline = false` ? CSharpier isn't looking at that setting, so it seems odd that 0.25.0 works but 0.26.X requires that to be true.

**Comment by loraderon** [comment]
I ended up adding a `.csharpierrc` with `endOfLine: auto`. 

I also think that this is a good enough workaround and the issue is very "searchable" so I think that it can be closed.

**Comment by Odonno** [comment]
This issue is coming back... And I kept `end_of_line = auto` in the `.editorconfig`.

Any idea? @belav
