### ISSUE TITLE
Configuration files not respected for stdin after version 0.26.0

### ISSUE THREAD

**Issue by kikniknik** [belav/csharpier#1028]
After version 0.26.0, that added support for editorconfig, it seems that configuration files (.csharpierrc and .editorconfig) are not respected when reading from stdin. Last version that reads `printWidth` from a `.csharpierrc` file in current directory is 0.25.0.

**Comment by belav** [comment]
There wasn't any code coverage on that case, sorry about that! I'm planning on releasing 0.26.3 within the next couple of days.
