### ISSUE TITLE
How to use CSharpier to format C# code in memory

### ISSUE THREAD

**Issue by komyg** [belav/csharpier#1029]
Hi,

I have a Node app that dynamically generates C# files, and I am trying to use CSharpier to format them.

Unfortunately, the generated files are going through CSharpier and returning unchanged, even though some of them should definitely have been re-formatted.

Here is what I am doing:

1. Generate the C# code.
2. Send it to CSharpier through the stdin.
3. Ge the response from the stdout.
4. Write the file to disk.

And here is my code:

```ts
import logger from '@sdk-gen/logger';
import { spawn } from 'child_process';

export async function runCSharpier(code: string, outputPath: string): Promise<string> {
  const separator = '\u0003';

  return new Promise<string>((resolve, reject) => {
    logger.info(`Running csharpier formatter for: ${outputPath}`);
    const formatter = spawn(
      'dotnet csharpier',
      ['--pipe-multiple-files', '--write-stdout', '--loglevel Debug'],
      {
        stdio: 'pipe',
        shell: true,
      },
    );
    const formattedCode: Buffer[] = [];

    formatter.stdout.on('data', (chunk): void => {
      console.log('DATA', chunk);
      formattedCode.push(chunk);
    });

    formatter.stderr.on('data', (err: unknown): void => {
      const error = err as Error;
      const message = error.message || error.toString();
      reject(message);
    });

    formatter.on('close', (): void => {
      formatter.removeAllListeners();
      const formattedCodeStr = Buffer.concat(formattedCode).toString();
      const separatorIndex = formattedCodeStr.indexOf(separator);
      resolve(formattedCodeStr.substring(0, separatorIndex));
    });

    formatter.stdin.write(outputPath);
    formatter.stdin.write(separator);
    formatter.stdin.write(code);
    formatter.stdin.write(separator);
    formatter.stdin.end();
    console.log('FINISHED');
  }).catch((error: string) => {
    logger.warn('Problems prettifying code.', { error: error });
    return code;
  });
}
```

I think that this problem may be happening because all calls to CSharpier seem to require an existing file on disk. Is this the case?

Do I have to change my flow to be something like:

1. Generate the C# code.
2. Write the unformatted code to disk.
3. Send it to CSharpier through the stdin.
4. Get the response from the stdout.
6. Update the existing file with the formatting changes.

Or maybe something like:

1. Generate the C# code.
2. Write the unformatted code to disk.
3. Call CSharpier on the generated folder.

Could you help me?

**Comment by Swimburger** [comment]
Did you get this to work, can you share your solution?
