### ISSUE TITLE
VS Code extension fails to use its .cache dotnet tool on macOS

### ISSUE THREAD

**Issue by Meligy** [belav/csharpier#1033]
First, thanks a lot for all the great work on CSharpier.

I have tried it and it worked great when setup in the project repository.

Now I'm trying to use it by default also.

For some reason, if I don't set the global path manually in settings, when I attempt to format a C# file with CSharpier, I get an error.

Debug output:

```jsonc
["INFO" - 13:50:07] Initializing csharpier-vscode
["INFO" - 13:50:17] Formatting started for /Users/meligy/code/meligy/MyDaemonApp/Program.cs.
["DEBUG" - 13:50:17] /Users/meligy/.vscode-insiders/extensions/csharpier.csharpier-vscode-1.5.0/build
["DEBUG" - 13:50:17] /Users/meligy/.vscode-insiders/extensions/csharpier.csharpier-vscode-1.5.0/build
["DEBUG" - 13:50:17] Ensure there is a csharpier process for /Users/meligy/code/meligy/MyDaemonApp
["DEBUG" - 13:50:17] Looking for /Users/meligy/code/meligy/MyDaemonApp/*.csproj
["DEBUG" - 13:50:17] Looking at /Users/meligy/code/meligy/MyDaemonApp/MyDaemonApp.csproj
["DEBUG" - 13:50:17] Looking for /Users/meligy/code/meligy/MyDaemonApp/.config/dotnet-tools.json
["DEBUG" - 13:50:17] Looking for /Users/meligy/code/meligy/*.csproj
["DEBUG" - 13:50:17] Looking for /Users/meligy/code/meligy/.config/dotnet-tools.json
["DEBUG" - 13:50:17] Looking for /Users/meligy/code/*.csproj
["DEBUG" - 13:50:17] Looking for /Users/meligy/code/.config/dotnet-tools.json
["DEBUG" - 13:50:17] Looking for /Users/meligy/*.csproj
["DEBUG" - 13:50:17] Looking for /Users/meligy/.config/dotnet-tools.json
["DEBUG" - 13:50:17] Looking for /Users/*.csproj
["DEBUG" - 13:50:17] Looking for /Users/.config/dotnet-tools.json
["DEBUG" - 13:50:17] Looking for //*.csproj
["DEBUG" - 13:50:17] Looking for /.config/dotnet-tools.json
["DEBUG" - 13:50:17] Unable to find dotnet-tools.json, falling back to running dotnet csharpier --version
["DEBUG" - 13:50:18] dotnet csharpier --version output 0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9
["DEBUG" - 13:50:18] dotnet csharpier --version output: 0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9
["DEBUG" - 13:50:18] Removing directory at /Users/meligy/.cache/csharpier/0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9 because it appears to be corrupted
["DEBUG" - 13:50:18] Running dotnet tool install csharpier --version 0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9 --tool-path "/Users/meligy/.cache/csharpier/0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9"
["DEBUG" - 13:50:20] dotnet csharpier --version output: 0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9
["INFO" - 13:50:20] Formatted in 2832.396915972233ms
["DEBUG" - 13:50:20] result is empty

```

The command seems like it should work, based on:

<img width="810" alt="image" src="https://github.com/belav/csharpier/assets/171637/aa320ea1-02cb-4912-9f12-55745e69c205">

The workaround is to set the default dotnet global tool location as a custom option:

```json
  "csharpier.dev.customPath": "/Users/meligy/.dotnet/tools"
```

Not sure how this might work when opening projects with local CSharpier tools though.

As a side note, this path does not work with `~/` or `$HOME/`. That's why I had to put it this way.

### Update

Please see first reply for more investigation.

**Comment by Meligy** [comment]
I tried removing the extension, quitting VS Code, then deleting the folder `/Users/meligy/.cache/csharpier`, then starting VS Code and installing the extension again.

But it still did not work:

```jsonc
["INFO" - 14:09:37] Initializing csharpier-vscode
["DEBUG" - 14:09:38] /Users/meligy/.vscode-insiders/extensions/csharpier.csharpier-vscode-1.5.0/build
["DEBUG" - 14:09:38] Ensure there is a csharpier process for /Users/meligy/code/meligy/MyDaemonApp
["DEBUG" - 14:09:38] Looking for /Users/meligy/code/meligy/MyDaemonApp/*.csproj
["DEBUG" - 14:09:38] Looking at /Users/meligy/code/meligy/MyDaemonApp/MyDaemonApp.csproj
["DEBUG" - 14:09:38] Looking for /Users/meligy/code/meligy/MyDaemonApp/.config/dotnet-tools.json
["DEBUG" - 14:09:38] Looking for /Users/meligy/code/meligy/*.csproj
["DEBUG" - 14:09:38] Looking for /Users/meligy/code/meligy/.config/dotnet-tools.json
["DEBUG" - 14:09:38] Looking for /Users/meligy/code/*.csproj
["DEBUG" - 14:09:38] Looking for /Users/meligy/code/.config/dotnet-tools.json
["DEBUG" - 14:09:38] Looking for /Users/meligy/*.csproj
["DEBUG" - 14:09:38] Looking for /Users/meligy/.config/dotnet-tools.json
["DEBUG" - 14:09:38] Looking for /Users/*.csproj
["DEBUG" - 14:09:38] Looking for /Users/.config/dotnet-tools.json
["DEBUG" - 14:09:38] Looking for //*.csproj
["DEBUG" - 14:09:38] Looking for /.config/dotnet-tools.json
["DEBUG" - 14:09:38] Unable to find dotnet-tools.json, falling back to running dotnet csharpier --version
["DEBUG" - 14:09:38] dotnet csharpier --version output 0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9
["DEBUG" - 14:09:38] Running dotnet tool install csharpier --version 0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9 --tool-path "/Users/meligy/.cache/csharpier/0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9"
["DEBUG" - 14:09:40] dotnet csharpier --version output: 0.26.2+d01362adf9f5163f0bda787a0e60888f12922fb9
["INFO" - 14:09:44] Formatting started for /Users/meligy/code/meligy/MyDaemonApp/Program.cs.
["DEBUG" - 14:09:44] /Users/meligy/.vscode-insiders/extensions/csharpier.csharpier-vscode-1.5.0/build
["INFO" - 14:09:44] Formatted in 0.7472090125083923ms
["DEBUG" - 14:09:44] result is empty
```

**Comment by Meligy** [comment]
Another workaround is downgrading the extension from v1.5.0 to v1.3.6, as v1.3.6 does not seem to be affected by this issue, and v1.5.0 changelog only shows "Improved error handling and reporting around csharpier failing to install or run".

**Comment by per-johansson-74** [comment]
1.5.0 also broke on windows if you have space in user foldername. 
Exception while running 'dotnet csharpier --version' in C:\Users\My UserName\AppData\Local\CSharpier\0.25.0
"'C:\\Users\\My' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

**Comment by Meligy** [comment]
> 1.5.0 also broke on windows if you have space in user foldername.

@per-johansson-74 can you please report this as a separate issue? The issue you are replying to is about macOS and not related to spaces in folder paths.

Thanks a lot.

**Comment by belav** [comment]
@Meligy @per-johansson-74 
I'll have fixes for both of these issues out shortly, they are both quick fixes. I just want to make sure I can recreate the problem to double check my work.

**Comment by Meligy** [comment]
Thanks a lot for the super fast response.

v1.5.1 solves the issue for me ❤️

However, one question for you...

Why does the extension ask for a CSharpier global install if it installs a version in `.cache`?
(I only realised that it installs a `.cache` version when debugging this issue)

**Comment by belav** [comment]
> Why does the extension ask for a CSharpier global install (And does not format without having either a local or a global install) if it installs a version in .cache anyway?

I wrote up an issue yesterday that covers the background of how it ended this way - #1036

I'm going to add another note to that because maybe it doesn't really make sense to ask if a user wants to install globally if the extension then just installs it into a custom location. Local versions need to be a specific version to avoid conflicts in formatting between team members,

**Comment by Meligy** [comment]
OK. Let's keep this conversation in https://github.com/belav/csharpier/issues/1036 then. This issue (the failures) is resolved.

Thanks again.
