### ISSUE TITLE
Simple chained attribute access is split into multiple lines on 0.26

### ISSUE THREAD

**Issue by Jackenmen** [belav/csharpier#1043]
Reproduction:
```cs
class X
{
    private void Method()
    {
        Application.Current.Dispatcher.Invoke(() =>
        {
            Console.WriteLine("hi!");
        });
    }
}
```

On 0.25.0, the above code is already formatted properly.

On 0.26.3, it is transformed into this:
```cs
class X
{
    private void Method()
    {
        Application
            .Current
            .Dispatcher
            .Invoke(() =>
            {
                Console.WriteLine("hi!");
            });
    }
}
```

I believe this was introduced by #967 and while I agree that long chains should be split, this seems a bit too eager.

**Comment by belav** [comment]
I'm including these comments in #1010, which is slightly different but around the same formatting changes in 0.26.0
