### ISSUE TITLE
Figure out IDE support

### ISSUE THREAD

**Issue by belav** [belav/csharpier#11]
What options are there currently for getting csharpier to run in an IDE?
Could plugins for the IDE's be developed?

**Comment by belav** [comment]
Added instructions for configuring a file watcher in Rider.

**Comment by shocklateboy92** [comment]
Another option is to create a build task that formats code pre-compile.

That way, one can get enforce consistent styling for their whole team despite everyone using different tools.

**Comment by belav** [comment]
The way we've used prettier at work is to have the build server check that the code is formatted, but not actually do the formatting.
That makes sure everyone is formatting their code, which helps avoid conflicts.
But then I often forget to format my code before pushing it, and have to do it when our build server complains to me.
So maybe the debug build could have a task for formatting, and the release build could have a task for validating the code is already formatted.
Either way, I think a build task makes sense, and if the build task is configurable people can use it in a way that works for them.

**Comment by belav** [comment]
Plugins are created/being created.
