### ISSUE TITLE
Collection expressions should be supported

### ISSUE THREAD

**Issue by ShawnTheBeachy** [belav/csharpier#1107]
**Input:**
```c#
public sealed class Fruit
{
    public List<string> Colors { get; init; } = [];
}
```

**Expected behavior:**
This should work, but using collection expressions breaks CSharpier. The file will not be formatted.

**Comment by belav** [comment]
Are you on an older version? Collection expressions support was added in at least 0.26, possibly somewhat supported before that.

**Comment by ShawnTheBeachy** [comment]
Oh... I was updating my global install, but not the project-level install 🤦‍♂️. Working now, thanks!

**Comment by belav** [comment]
> Oh... I was updating my global install, but not the project-level install 🤦‍♂️. Working now, thanks!

No problem! My co-worker ran into something related last week, apparently `dotnet-csharpier` will run the global install and `dotnet csharpier` will run the local install, and those versions were mismatched on his system.
