### ISSUE TITLE
Allow empty/blank lines in object initializers

### ISSUE THREAD

**Issue by Qtax** [belav/csharpier#1110]
In larger object initializers it is helpful to group properties into logical groups/blocks separated by an empty line and/or a blank line followed by a comment.

**Input:**
```csharp
var templateVars = new
{
	date_trunc = filter.AggregationType.GetDateTruncString(true),

	date_from = from.ToString("yyyy-MM-dd"),
	date_to = to.ToString("yyyy-MM-dd"),

	compare_from = compareFrom.ToString("yyyy-MM-dd"),
	compare_to = compareTo.ToString("yyyy-MM-dd"),

	// Pagination
	order_by = sortOrder switch
	{
		StreamGamesSortBy.HoursWatched => "watched_hours",
		StreamGamesSortBy.AverageCCV => "viewers_avg",
		StreamGamesSortBy.PeakCCV => "viewers_max",
		_ => throw new ArgumentOutOfRangeException()
	},
	order_direction = sortDir switch
	{
		OrderDirection.Desc => "DESC",
		OrderDirection.Asc => "ASC",
		_ => throw new ArgumentOutOfRangeException()
	},
	limit = filter.Take,
	offset = filter.Skip
};
```

**Output:**
```csharp
var templateVars = new
{
	date_trunc = filter.AggregationType.GetDateTruncString(true),
	date_from = from.ToString("yyyy-MM-dd"),
	date_to = to.ToString("yyyy-MM-dd"),
	compare_from = compareFrom.ToString("yyyy-MM-dd"),
	compare_to = compareTo.ToString("yyyy-MM-dd"),
	// Pagination
	order_by = sortOrder switch
	{
		StreamGamesSortBy.HoursWatched => "watched_hours",
		StreamGamesSortBy.AverageCCV => "viewers_avg",
		StreamGamesSortBy.PeakCCV => "viewers_max",
		_ => throw new ArgumentOutOfRangeException()
	},
	order_direction = sortDir switch
	{
		OrderDirection.Desc => "DESC",
		OrderDirection.Asc => "ASC",
		_ => throw new ArgumentOutOfRangeException()
	},
	limit = filter.Take,
	offset = filter.Skip
};
```

**Expected behavior:**

Allow single empty lines in object initializers: between initialized properties and/or comments.
This would be consequent with how blank lines are allowed between lines of regular code and/or comments.

Does this seem like an acceptable change to you?

**Comment by belav** [comment]
I don't see a good reason to not allow it, it does keep things consistent with other places that allow new lines.

Your example was for an anonymous object, which is a different node than a regular object initializer. But I made changes to allow it in either place + other types of initializers (dictionaries, arrays, etc).

**Comment by belav** [comment]
I take that last part back. Dictionaries and arrays are a bit trickier. This will just be for objects (anonymous or not) for now.

**Comment by Qtax** [comment]
Great, thanks! And as you pointed out it would be nice with same behaviour in dictionaries and arrays too.
We just started using csharpier in our project, so just starting to notice some things.

A small possibly related issue with object initializers that I don't really care about that maybe you'd like you know of:

When formatting this (in 0.26.7):

```
		var foo = new {
			foo = 1,


			// empty lines after a comment are not removed


			bar = 2,
		};
```

You get this:
```
		var foo = new
		{
			foo = 1,
			// empty lines after a comment are not removed


			bar = 2,
		};
```

Would prefer/expect:
```
		var foo = new
		{
			foo = 1,

			// empty lines after a comment are not removed

			bar = 2,
		};
```

Or at least that empty lines after comments are treated the same as before.

**Comment by belav** [comment]
The empty lines sticking around after a comment is a known issue I have somewhere in the backlog. I believe it happens with comments anywhere. No one has complained so it hasn't been prioritized yet. Thanks for letting me know!
