### ISSUE TITLE
Weird formatting of linq chain

### ISSUE THREAD

**Issue by Rudomitori** [belav/csharpier#1130]
**Input:**
```C#
var something_________________________________________ = x.Answers
    .Select(y => (DateTime?)y.CreatedAt)
    .Min();
```
**Output:**
```C#
var something_________________________________________ = x.Answers.Select(y =>
    (DateTime?)y.CreatedAt
)
    .Min();
```

**Expected behavior:**
```C#
var something_________________________________________ = x.Answers
    .Select(y => (DateTime?)y.CreatedAt)
    .Min();

// or
var something_________________________________________ = x
    .Answers.Select(y => (DateTime?)y.CreatedAt)
    .Min();

// or
var something_________________________________________ = x
    .Answers
    .Select(y => (DateTime?)y.CreatedAt)
    .Min();
```

**Comment by loraderon** [comment]
I think this is the same issue as #1079

**Comment by belav** [comment]
This seems related to #1079, but this particular case did work quite a ways back. I was having a bit of trouble tracking down how exactly the regression was introduced so went back quite a few versions.

This appeared in 0.26.7 and I was able I track down the source of the problem.  The changes in https://github.com/belav/csharpier/pull/967 were somewhat dependant on this single line I reverted in https://github.com/belav/csharpier/pull/1074. I still need to find a solution that makes all of the updated test cases happy.

Side note - running multiple versions of the playground would be nice to track down regressions like this.
Or maybe a utility that uses docker to show the changes over versions for some code. But I don't know that this comes up often enough to be worth the effort.

**Comment by shocklateboy92** [comment]
> Side note - running multiple versions of the playground would be nice to track down regressions like this.
Or maybe a utility that uses docker to show the changes over versions for some code. But I don't know that this comes up often enough to be worth the effort.

I think git bisect is what you're after:
https://git-scm.com/docs/git-bisect

Especially since you can write a trivial test and a script to repro it, you can even have it run/find the commit automatically:
https://git-scm.com/docs/git-bisect#_bisect_run

**Comment by belav** [comment]
@shocklateboy92 thanks for the link, that would have helped make what I did a bit easier!

@jods4 I happened to make changes that I believe take care of your second example.
When the initial identifier is <= 4 characters, there was logic to keep the first group of the chain on the same line.
Its main goal was to prevent formatting like this from occurring.
```c#
x
    .CallMethod____________________________________________________________()
    .CallMethod____________________________________________________________();
```

That logic is tweaked a bit, and results in your example like so.

```c#
// Formatted with 0.27.1
var AlternateKeys =
    entityType.Keys.Count > 0
        ? entityType
            .Keys.Select(k => new KeyTemplate
            {
                Name = k.DisplayName.GetDisplayName(),
                ClassName = AddSuffix(k.DisplayName.GetFriendlyName("<missing key name>"), "Key"),
                Fields = k
                    .KeyAttributes.Select(f => new KeyValuePair<string, PropertyTemplate>(
                        f,
                        Properties.SingleOrDefault(x => x.LogicalName == f)
                    ))
                    .ToList(),
            })
            .ToList()
        : null;

**Comment by jods4** [comment]
Looks good to me! 

@belav Aside: `entityType.Keys.Count > 0` is not kept on the same line as `var AlternateKeys =` because of the Rectangle Rule?
I feel like Conditionals are one more instance where it would just look better if we broke it. 
IMHO it creates 2 almost empty lines, increases indentation and doesn't really improve readability.
