### ISSUE TITLE
Operator placement in long if statements

### ISSUE THREAD

**Issue by tim-altitudegames** [belav/csharpier#1149]
Using 0.27.1, I feel there could be a minor improvement with how long statements are separated with regards to the placement of the operators. Having all the variables vertically aligned with each other to me seems a little easier to read with the `&&` placed at the end of the previous line rather than the start of the next one. This would be similar behaviour to what prettier does too.

**Input:**
```
var theNumberOne = 1;
var theNumberTwo = 2;
var theNumberThree = 3;
var theNumberFour = 4;
var theNumberFive = 5;
var theNumberSix = 6;

if (theNumberOne == 1 && theNumberTwo == 2 && theNumberThree == 3 && theNumberFour == 4 && theNumberFive == 5 && theNumberSix == 6)
{
    // They are who they say they are
}
```

**Output:**
```
var theNumberOne = 1;
var theNumberTwo = 2;
var theNumberThree = 3;
var theNumberFour = 4;
var theNumberFive = 5;
var theNumberSix = 6;

if (
    theNumberOne == 1
    && theNumberTwo == 2
    && theNumberThree == 3
    && theNumberFour == 4
    && theNumberFive == 5
    && theNumberSix == 6
)
{
    // They are who they say they are
}
```

**Expected behavior:**
```
var theNumberOne = 1;
var theNumberTwo = 2;
var theNumberThree = 3;
var theNumberFour = 4;
var theNumberFive = 5;
var theNumberSix = 6;

if (
    theNumberOne == 1 &&
    theNumberTwo == 2 &&
    theNumberThree == 3 &&
    theNumberFour == 4 &&
    theNumberFive == 5 &&
    theNumberSix == 6
)
{
    // They are who they say they are
}
```

**Comment by Rudomitori** [comment]
I prefer how CSharpier formats it now. It makes easier to understand the logic of the condition when you have not trivial combination of `&&` and `||`

**Comment by belav** [comment]
Operators at the beginning of long statements is the widely accepted best practice. If I recall correctly from this super long prettier issue about it, someone just picked putting them at the end and they have been reluctant to finally move them to the beginning. https://github.com/prettier/prettier/issues/3806

There is a lot of discussion in that issue as well about the pros of operators at the beginning.

**Comment by tim-altitudegames** [comment]
Fair enough, reading through that issue I can see why, also I see you referenced this issue https://github.com/belav/csharpier/issues/442 as well in case anyone else sees this
