### ISSUE TITLE
CSharper does not recognize class primary constructor

### ISSUE THREAD

**Issue by cebon** [belav/csharpier#1166]
**Input:**

When we try to enter a class with a primary constructor (c#12)

```
public class MyClass(string value) 
{   
    public string Value { get; };
}
```

**Output:**

CSharpier doesn't work, et return the following message

 _Failed to compile so was not formatted._

**Comment by Rudomitori** [comment]
What version of CSharpier do you use? 

To check the version use ` dotnet tool list` or ` dotnet tool list -g`

**Comment by cebon** [comment]
I was using version 0.20 installed from the Rider plugin, which had not been updated automatically.

By manually updating csharpier, it works.

Sorry for the inconvenience
