### ISSUE TITLE
Break before or after binary operator

### ISSUE THREAD

**Issue by belav** [belav/csharpier#117]
For now csharpier breaks after the binary operator because most repositories seem to follow that standard.

The standard seems to be breaking after the binary operator.
```c#
if (
    SomeLongVariableName ||
    AnotherLongVaribleName ||
    YetAnotherLongVariableName ||
    AndOneMore
) { }
```
Prettier formats this way.
Most public repos seem to format this way.
Black formats by breaking before the operator, like so
```c#
if (
    SomeLongVariableName
    || AnotherLongVaribleName
    || YetAnotherLongVariableName
    || AndOneMore
) { }
```
The argument for why is given here https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator
If we do decide to break before, then we may want to format like this
```c#
if (SomeLongVariableName
    || AnotherLongVaribleName
    || YetAnotherLongVariableName
    || AndOneMore
) { }
```

**Comment by belav** [comment]
Adding comments from @shocklateboy92 here so they don't get lost.

> Okay, the more I look at the resulting changes, the more I think that the operator for a binary expression should be in the new line.

> There's no indent in these, so when skimming through it isn't immediately apparent that the new line is a continuation of the previous line's content.
Putting the operator at the beginning of the line does many things in one go. It:

> Gives us a "semi-indent" for free (using less characters as well)
Let's you know this is part of the previous statement while skimming through
Makes it immediately apparent how this is related to the previous line. (E.g. + or && etc.)

**Comment by belav** [comment]
Prettier discussion on switching to breaking before.
https://github.com/prettier/prettier/issues/3806

**Comment by shocklateboy92** [comment]
From their discussion it sounds like there are distinct advantages to
breaking before the operator and no real reasons for breaking after. The
only reason prettier does it that way is because it's too expensive to
change.

Since we have no such debt we should go ahead and implement according to
the proposal in the issue.

**Comment by belav** [comment]
Closing. We decided to break before binary operators.
