### ISSUE TITLE
Add more options to CodeFormatterOptions

### ISSUE THREAD

**Issue by Phault** [belav/csharpier#1172]
I'm creating a wrapper plugin for integrating Csharpier with [dprint](https://dprint.dev), but I've hit a snag as the Csharpier.Core package only exposes CodeFormatterOptions, which currently only contains the setting for PrintWidth.

Would it be possible to get all the options exposed? I'm willing to create a PR to add this, although I'd prefer knowing the reasoning for the current split of CodeFormatterOptions and PrinterOptions first.

**Comment by belav** [comment]
If I recall correctly, I added `CodeFormatterOptions` when there was just the single option for width, and then missed adding tabs/indent size. `PrinterOptions` contains a lot of options that didn't make sense to expose in `CSharpier.Core` which I believe is why I split them originally.

I'm not in love the the names in `PrinterOptions` - I'm thinking that `TabWidth` changes to `IndentSize` on `CodeFormatterOptions` (to line up with the editorconfig name). And maybe `UseTabs` should be an enum called `IndentStyle`, but an enum for just two options could be overkill.

I have no problem exposing the options so go ahead with the PR.
