### ISSUE TITLE
editorconfig dotnet_sort_system_directives_first = false ignored

### ISSUE THREAD

**Issue by andrewdavey** [belav/csharpier#1177]
I've upgraded the dotnet-csharpier tool from 0.23.0 to 0.27.2. It now wants to change the sort order of all my `using` directives.

My `.editorconfig` has:

```
dotnet_sort_system_directives_first = false
```

But it seems this is ignored by csharpier.

Is there anyway to avoid needing to reformat every file in my repository?

**Comment by belav** [comment]
CSharpier does not take into account `dotnet_sort_system_directives_first` so yeah, the latest version will most likely reformat all files in your repostory.

**Comment by andrewdavey** [comment]
Thank you for the quick response on this. I'll apply the new formatting.
