### ISSUE TITLE
CSharpier can not support slice[] grama,

### ISSUE THREAD

**Issue by dumbnessrf** [belav/csharpier#1185]
```C#
  var a="";
var b = new List<string>();
    b=[a];
```
Can not format code, unless i change code like this
```C#
  var a="";
var b = new List<string>();
   b=new List<string>(){a};
```

Net Sdk: net48
C# version: 12

**Comment by belav** [comment]
You must be on an older version of CSharpier, this formats just fine on the playground. I believe support for it was added as of 0.26.0 or so.

**Comment by belav** [comment]
CSharpier is versioned independently from the extension for CSharpier. The extension is just a wrapper that uses whichever version of csharpier is configured in your project or installed globally.

You can use `dotnet tool update csharpier` to update csharpier. You'll need a -g flag if you have it installed globally. And you'll want to restart VS afterwards to make sure it detects the updated version of csharpier.
