### ISSUE TITLE
Expose IncludeGenerated in CodeFormatterOptions

### ISSUE THREAD

**Issue by Vhab** [belav/csharpier#1215]
**Environments:**

- CSharpier Version: 0.27.3
- Running CSharpier via: API
- Operating System: Windows
- .csharpierrc Settings: N/A
- .editorconfig Settings: N/A

We would like to use CSharpier to format generated code before writing it.
Our generated code includes the `<auto-generated>` header causing CSharpier to skip it.
It would be nice for `IncludeGenerated` to be added to `CodeFormatterOptions` to disable this behavior.

**Comment by belav** [comment]
Sounds totally reasonable!
