### ISSUE TITLE
not support " = []"

### ISSUE THREAD

**Issue by AlvisZhang** [belav/csharpier#1219]
**Input:**
List<BsonDocument> list = [];

**Output:**

 formatter stop work，unless replace "[]" with "new()"

**Expected behavior:**

can format use "= [];"

**Comment by belav** [comment]
Collection expressions are supported, you must be on an old version of csharpier. Note that csharpier is versioned separately from the ide extensions and updating the extension does not actually update csharpier.

**Comment by stevenfishli** [comment]
I'm using dotnet 8.0.1 and cshapier 1.6.0
same error

string[] test = ["1", "2"];
Failed to compile so was not formatted.\n  (40,29): error CS1525: Invalid expression term '['\n"

If I use this `string[] test = new string[] { "1", "2" };`, there is no problem.

**Comment by stevenfishli** [comment]
I use this command `dotnet csharpier --version` to get the version.
It is 0.22.1.
I have installed vs code extension cshapier 1.6.0.
I see the latest version is 0.28 at gitlab.
How can I update the version to 0.28?

**Comment by stevenfishli** [comment]
Finally, I know my problem.
I use wrong version at .config/dotnet-tools.json

```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "CSharpier": {
      "version": "0.28.0",
      "commands": [
        "dotnet-csharpier"
      ]
    }
  }
}
```

I guess someone is like me to follow this link to setup husky
https://csharpier.com/docs/Pre-commit

Then, we use wrong version 0.22.1 and it is a very old version.
Maybe better to use X.XX.X and remind others to input latest version.

**Comment by belav** [comment]
I updated the doc to remove the hardcoded version number.
