### ISSUE TITLE
dotnet-csharpier process never closes

### ISSUE THREAD

**Issue by mejobloggs-cw** [belav/csharpier#1231]
Is this a bug, or intended behaviour?

If I open Visual Studio, and a C# file, then close Visual Studio, I notice dotnet-csharpier is still running in Task Manager

If I repeat this 10x, I will have no Visual Studio open, but 10x dotnet-csharpier.exe in Task Manager.

VS 2022 Preview 4.0
VS CSharpier Extension 1.5.2
Csharpier: 0.28.1

**Comment by belav** [comment]
This wasn't intended, I have code that I assumed was killing off the running csharpier process when VS was closed, but it doesn't appear to be working. I'll hopefully have a fix for it soon.

**Comment by belav** [comment]
Do you have "Use CSharpier Server" turned on? I was only able to reproduce it while that was on. The option was intended for testing a new way of communicating with CSharpier, and there was a bug there with not actually killing dotnet-csharpier if that option was on.

With that option off, it kills off dotnet-csharpier as expected.

I'll get this fix out shortly + make the csharpier server feature official when using 0.28+
