### ISSUE TITLE
Comment between attributes violates SA1515

### ISSUE THREAD

**Issue by maurobringolf** [belav/csharpier#1252]
**Input:**

```csharp
public class C {

    [A]
    
    // moves up
    [B]
    public void A()
    {
        var z = 1;
        
        // stays here
        var y = 2;
    }
}
```

**Output:**

```csharp
public class C
{
    [A]
    // moves up
    [B]
    public void A()
    {
        var z = 1;

        // stays here
        var y = 2;
    }
}
```

**Expected behavior:**
The autoformatting causes the code not to comply with [SA1515](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1515.md).
According [to the docs](https://csharpier.com/docs/IntegratingWithLinters) this rule is not in conflict with the CSharpier format.
I expect the output to build without formatting warnings when configured as described.

---

As far as I can tell this can be resolved in two ways:

1. Keep whitespace before comments in all cases (if that's possible).
2. Add SA1515 to the to-be-disabled rules

I would favor the second option.

**Comment by belav** [comment]
There is already logic for forcing a new line before the first attribute and removing blank lines between attributes. After looking into it - getting all of that to play nice with keeping/adding new lines before comments between attributes won't be straightforward. I'm good with adding SA1515 to the to-be-disabled list.
