### ISSUE TITLE
Support custom extensions in .editorconfig

### ISSUE THREAD

**Issue by belav** [belav/csharpier#1273]
#1251 is adding the ability to customize options based on file path, which will also allow non-standard file extensions to be formatted.

This issue is for adding support for this to .editorconfig

**Comment by viceice** [comment]
Would this also enable setting `preprocessorSymbolSets` via `.editorconfig`? That option force me to use `.csharpierrc` for configuration.

**Comment by belav** [comment]
> Would this also enable setting `preprocessorSymbolSets` via `.editorconfig`? That option force me to use `.csharpierrc` for configuration.

@viceice `preprocessorSymbolSets` hasn't been supported as an option for a few versions now. CSharpier can parse the conditions in the preprocessor directives and build its own sets for each file.

**Comment by viceice** [comment]
> > Would this also enable setting `preprocessorSymbolSets` via `.editorconfig`? That option force me to use `.csharpierrc` for configuration.
> 
> @viceice `preprocessorSymbolSets` hasn't been supported as an option for a few versions now. CSharpier can parse the conditions in the preprocessor directives and build its own sets for each file.

oh, I missed that change 😅. so I'll drop the explicit config in favor of editor config. 🤗
