### ISSUE TITLE
Ditch csharpier-repos

### ISSUE THREAD

**Issue by belav** [belav/csharpier#128]
Instead of having a mono repo of public files that is essentially a snapshot of the code from them, we can hopefully do the following.

1. Add a json file with a list public repos to check out
2. Add a .csharpierrc file that includes the files that will be ignored from the public repos
3. Modify the github action for format_repositories to check out all repositories from the json file into the same location as the .csharpierrc, then format them all.

This means we can easily add new repos and we continue to test the latest versions of those repos, which should help catch more edge cases.

**Comment by jrobertson-insite** [comment]
2. Should be .csharpierignore see [comment on issue 140](https://github.com/belav/csharpier/issues/140#issuecomment-826117645)

**Comment by belav** [comment]
Prettier does something similar. See https://github.com/prettier/prettier-regression-testing/blob/master/src/projects.ts
