### ISSUE TITLE
Editorconfig new_line_before support

### ISSUE THREAD

**Issue by isaksky** [belav/csharpier#1289]
For C#, I got used to `csharp_new_line_before_X` in .editorconfig to support a brace style more like mainstream languages (JavaScript, Java, etc). This is supported by Visual Studio, LinqPad, and I think Rider. Is this something you'd be open to supporting (or accepting a PR for)?

**Input:**

.editorconfig:

```editorconfig
[*.cs]
csharp_new_line_before_open_brace = none
csharp_new_line_before_else = false
csharp_new_line_before_catch = false
csharp_new_line_before_finally = false
```

ClassName.cs:
```csharp
public class ClassName {
    public void CallMethod() { 
        this.LongUglyMethod("1234567890", "abcdefghijklmnopqrstuvwxyz", "ABCDEFGHIJKLMNOPQRSTUVWXYZ");
    }
}
```

**Output:**

```csharp
public class ClassName
{
    public void CallMethod()
    {
        this.LongUglyMethod(
            "1234567890",
            "abcdefghijklmnopqrstuvwxyz",
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        );
    }
}
```

**Expected behavior:**

```csharp
public class ClassName {
    public void CallMethod() {
        this.LongUglyMethod(
            "1234567890",
            "abcdefghijklmnopqrstuvwxyz",
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        );
    }
}
```

**Comment by belav** [comment]
> CSharpier provides a few basic options that affect formatting and has no plans to add more. It follows the [Option Philosophy](https://prettier.io/docs/en/option-philosophy.html) of prettier.

**Comment by pisolofin** [comment]
@isaksky if you want a start to implement that options in my branch https://github.com/pisolofin/csharpier-editorconfig/tree/feature/brackets

**Comment by snatvb** [comment]
@belav then you can save lines to avoid useless line breaks :)
just it's only one reason why I can't use the tool
