### ISSUE TITLE
Formatting may conflict with StyleCopAnalayzers

### ISSUE THREAD

**Issue by belav** [belav/csharpier#13]
We need to investigate which style cop rules need to be disabled to avoid conflicts with csharpier

**Comment by belav** [comment]
We should wait on this until after we decide if we are moving away from SpaceBrace - See #423

**Comment by belav** [comment]
Also .net 5 has moved to Microsoft.CodeAnalysis.NetAnalyzers, although the rule names may be the same.
See https://github.com/dotnet/roslyn-analyzers

**Comment by lara-ec** [comment]
Hi,
SA1516 (ElementsMustBeSeparatedByBlankLine) conflicts with csharpier, when you have a get/set that does a line break. stylecop wants a newline between get and set, csharpier removes the newline.

`private string a;

public string A
{
    get
    {
        return a + "this is a very long string that is this long so it can force a line break";
    }
    set { a = value; }
}`

**Comment by belav** [comment]
@lara-ec I am adding SA1516 to the list of rules that should be disabled. I am not sure if your intention when reporting it was that csharpier should add the extra line before the set.

When I looking into multiline accessors for properties (using https://github.com/belav/csharpier-repos), only 16% of them included a line between them if one of the two spanned multiple lines. I think it makes sense to have csharpier stick to that and remove the empty line.

SA1516 is also used to ensure there is a new line between method definitions, which csharpier doesn't currently have an opinion on. See #285. I think it makes sense for csharpier to starting adding the blank lines between methods. 87% of the methods in classes from csharpier-repos have a blank line before them.

**Comment by lara-ec** [comment]
@belav Yes, my intention was to have it on the list. :)

I don't have a strong opinion on it, but FWIW I agree with what you say.

**Comment by belav** [comment]
When 0.13.0 is released, I will update the docs with which stylecop rules conflict with csharpier.
