### ISSUE TITLE
System.Text.Json has high severity vulnerability

### ISSUE THREAD

**Issue by jamesfoster-excelpoint** [belav/csharpier#1303]
I've just tried building from source and get the following error

Warning As Error: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w

after updating visual studio and installing the latest version of the dotnet SDK (as per the link) I still get this when building the solution. I realise this might not be a problem with csharpier, per se. I removed the reference and only the netstandard2.0 target failed to build. Would it be possible to conditionally include the reference?

Any idea why I'm still getting this error after updating?

**Environments:**

- CSharpier Version:  7ab89d57798

**Comment by belav** [comment]
If you update the version of system.text.json in the Directory.Packages.props file you can resolve the warning. I have the warning fixed in my most recent unrelated PR and probably should have just split it off and gotten it merged before going out of town.
