### ISSUE TITLE
Rework the CLI to properly use commands + arguments.

### ISSUE THREAD

**Issue by belav** [belav/csharpier#1321]
Currently all arguments are available to csharpier but not all of them apply depending on what you are trying to do with csharpier.

Reworking the cli to use the subcommands from `System.CommandLine` will help with this.

Some examples of commands reworked
```
dotnet csharpier format . --loglevel None

dotnet csharpier check . --loglevel None

dotnet csharpier server --port 30000

dotnet csharpier pipe-files
```

Consider also removing the need to prefix things with `dotnet`, it is an option when building/publishing a dotnet tool.

**Comment by stefannikolei** [comment]
Should the log level be an Global option?

**Comment by stefannikolei** [comment]
I would work on this. Could we define the available commands with corresponding options in here?
