### ISSUE TITLE
Process cannot access the file "....net8.0\any\server.log" while running multiple extensions.

### ISSUE THREAD

**Issue by belav** [belav/csharpier#1324]
I ran into this while vscode was running and I ran rider, it would probably happen with multiple windows of the same ide as well. It will only affect csharpier server, so disabling that option will allow users to bypass it.

> java.lang.NumberFormatException: For input string: "Unhandled exception: System.IO.IOException: The process cannot access the file 'C:\Users\bela\AppData\Local\CSharpier\0.29.0\.store\csharpier\0.29.0\csharpier\0.29.0\tools\net8.0\any\server.log' because it is being used by another process."

Need to figure out how to log from multiple instances of the process.

**Comment by viceice** [comment]
Seeing it too, having multiple vscode and visual studio projects open 🙃
