### ISSUE TITLE
Sorting of usings with underscore differs from Visual Studio

### ISSUE THREAD

**Issue by RudyMauro-Datamind** [belav/csharpier#1327]
**Input:**

```csharp
using Api.Repositories._Core;
using Api.Repositories.Helpers;
```

**Output:**

```csharp
using Api.Repositories.Helpers;
using Api.Repositories._Core;
```
**Expected behavior:**
It should match the behavior of Visual Studio's "Sort usings"
```csharp
using Api.Repositories._Core;
using Api.Repositories.Helpers;
```

**Comment by seoj-trifork** [comment]
Are there some docs about sorting `using`? I was looking for a tool that does this, I didn't know Csharpier did it because I couldn't find it in the docs.
