### ISSUE TITLE
Empty Method now breaks

### ISSUE THREAD

**Issue by belav** [belav/csharpier#133]
This used to keep the { } on the same line. No need to break if there is nothing actually in the body.
```c#
        public virtual Castle.Components.DictionaryAdapter.IDictionaryBehavior Copy()
        { }
```
On the other hand this is past the 80 character limit, and doesn't break at all til the braces. But maybe that is fine?
```
        public override System.Collections.Generic.IEnumerable<string> GetDynamicMemberNames()
        { }
```

**Comment by shocklateboy92** [comment]
I think that's fine - making a special rule to go past the character limit
for this doesn't seem worth it.
