### ISSUE TITLE
Should namespaces not be indented?

### ISSUE THREAD

**Issue by belav** [belav/csharpier#135]
99% of c# files contain a single namespace, but every single one of those files has the namespace indented.
This essentially means that the default line width of csharpier is 76 instead of 80.
c# 10 is going to provide a way to namespace a file without braces - https://github.com/dotnet/csharplang/issues/137
Should csharpier just not indent the namespace? It looks kind of weird.
```c#
namespace Blah
{ // ensure there is a blank line after this when formatting.

public class ClassName
{
    public string ShortPropertyName { get; set; }

    public void Method()
    {
        CallSomethingElse();
    }
}

} // ensure there is a blank line before this when formatting.
```

**Comment by jrobertson-insite** [comment]
This looks less than great and defies almost every coding standard I've ever seen. I think waiting for the C#10 proposed feature and maybe auto-use that if there is only a single namespace in the file.

**Comment by shocklateboy92** [comment]
Personally, I'm leaning towards not indenting namespaces.
A coworker and I started looking into how csharpier formats our files and our first thought was that we'd have more space if namespaces weren't indented.

There's another case for not indenting that came up, (that I guess I should open a separate issue for): nested for loops.

**Comment by respel** [comment]
I'm just gonna repeat what I said elsewhere. We should stick with what the community is doing, especially in cases where the consensus is clear.
