### ISSUE TITLE
Suggestion - VS - Configuration hot reload

### ISSUE THREAD

**Issue by scabana** [belav/csharpier#1367]
**Environments**
- IDE Version: vs2022 pro
- Extension Version: 1.8.0
- CSharpier Version: 0.28.2 
*will NOT be the same as the extension version*
- Operating System: win11
- .csharpierrc Settings: doesn't exist
- .editorconfig Settings: 
  ```
  [*.cs]
  max_line_length = 160
  ```

**Steps to reproduce**

1. Have the VS extension installed
2. Open VS + solution
3. outside of VS, create a `.vs/$(SolutionName)/v17/csharpier.json` containing `"RunOnSave": true`
4. `ctrl-s` on a c# file in the previously opened VS

**Expected behavior**

The c# file should be formatted.

**Actual behavior**

The file based configuration has not been loaded from disk when the file changed.

**Experiment**

Updated `CSharpierOptions.cs`'s [`LoadAsync`](https://github.com/belav/csharpier/blob/356394035b3fcccfaa272a399a9603ec3845f72a/Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierOptions.cs#L95C3-L96C68) to contain for following code: 

```csharp
var filePath = await getFilePath();

static FileSystemWatcher Create(string filePath)
{
    FileSystemWatcher fsw = new FileSystemWatcher(Path.GetDirectoryName(filePath), Path.GetFileName(filePath));

    static void OnSomethingChanged(object sender, FileSystemEventArgs e)
    {
        ThreadHelper.Generic.BeginInvoke(() => Instance.Load());
    }

    fsw.Changed += OnSomethingChanged;
    fsw.Created += OnSomethingChanged;
    fsw.Renamed += OnSomethingChanged;
    fsw.EnableRaisingEvents = true;

    return fsw;
}

_fileSystemWatcher = _fileSystemWatcher ?? Create(filePath);

if (filePath == null || !File.Exists(filePath))
{
    return;
}
```

And now the config gets reloaded when the file changed. 

We are using some automation to enable CSharpier automatically when someone is using VS, the dev experience would be better if it didn't need a VS restart to be picked up.

I can open a PR with the updated code.

**Comment by belav** [comment]
This is a great suggestion, if you can open the PR I can get out an updated version of the extension. Thanks!

**Comment by scabana** [comment]
.assign
