### ISSUE TITLE
Support .NET 9

### ISSUE THREAD

**Issue by sin-ack** [belav/csharpier#1378]
.NET 9 just got released, would be cool if we could use Csharpier with it.

**Environments:**

- CSharpier Version: 0.29.2
- Running CSharpier via: dotnet cli
- Operating System: Gentoo Linux amd64
- .csharpierrc Settings: (empty)
- .editorconfig Settings: (empty)

**Steps to reproduce:**

1. Install .NET SDK 9.0.100
2. `dotnet tool install csharpier`
3. `dotnet dotnet-csharpier`

**Expected behavior:**

Nicely formatted code.

**Actual behavior:**

```
» dotnet dotnet-csharpier
You must install or update .NET to run this application.

App: /home/*snip*/.nuget/packages/csharpier/0.29.2/tools/net8.0/any/dotnet-csharpier.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /home/*snip*/tmp/dotnet-9.0/

The following frameworks were found:
  9.0.0 at [/home/*snip*/tmp/dotnet-9.0/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=linux-x64&os=gentoo.2.15
```

**Comment by sin-ack** [comment]
As a workaround, `dotnet tool --allow-roll-forward` lets Csharpier run for the time being, but I don't know if that causes issues.

**Comment by belav** [comment]
I've added support in #1318 which will be out with the next release. Just have a couple of things to finish up for that release. It also sounds like I may be able to change csharpier to roll forward automatically to avoid this for next time. I'll leave this open so I can look into that.

**Comment by JesperLundberg** [comment]
Just adding my request for getting support for dotnet 9 release... released. :)

Also, big thanks for your work. I don't understand how I could live without a formatter for so long before I started using CSharpier.

**Comment by liri2006** [comment]
Hi @belav, Any ETA when this would be released?

**Comment by belav** [comment]
@liri2006 support for net9 went out with 0.30.0, the work was done on https://github.com/belav/csharpier/issues/1318. I forgot to close out this issue.

**Comment by liri2006** [comment]
@belav, oops, did not check the actual csharpier version, only the Rider plugin one. Thanks!
