### ISSUE TITLE
Ignore generated files by default

### ISSUE THREAD

**Issue by belav** [belav/csharpier#140]
Should Csharpier by default ignore files that are named *.generated.cs? Is that a common naming convention?

What about files that include the auto-generated tag? That includes .cshtml.cs files and possibly others.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

**Comment by jrobertson-insite** [comment]
Yes, but I don't think there is any guarantee of what is or is not generated. There are countless ways to generate code (Visual Studio, T4, unit tests, etc). This could be a good use of a config option or file to denote glob patterns that indicate files to ignore. Maybe use the ubiquitous ".gitignore" glob style, ".csharpierignore".

**Comment by belav** [comment]
.csharpierignore has been proposed and is mentioned in https://github.com/belav/csharpier/issues/43
It still may be nice to ignore things by default. Some projects create generated files behind the scenes. Forcing everyone to add those types of files to an ignore list seems like a headache if we can just default it.

**Comment by shocklateboy92** [comment]
We can also add an option to read a .gitignore
