### ISSUE TITLE
CSharpier keeps adding a newline every time a file is formatted

### ISSUE THREAD

**Issue by bvanreeven** [belav/csharpier#1408]
**Input:**

Given the following, already correctly formatted, C# file:

```csharp
using System;

namespace MyCompany.MyNamespace;

// Comment block

```

Running CSharpier (v0.30.3) on the file (with the `--no-cache` flag) will add a newline between the `namespace` and the comment block every time the file is formatted.

Also, running CSharpier with the `--check` flag will mark the file as having a formatting issue.

**Output:**
* A newline is added to the file every time it is formatted.

**Expected behavior:**
* The file remains formatted the same way, even when running CSharpier multiple times.

**Comment by belav** [comment]
I remember taking a look at this awhile back after running into it somehow and thinking "this won't ever come up in the real world" when I couldn't find an obvious fix. I'll take another look at it
