### ISSUE TITLE
Add debug option to show what rule(s) caused the formatting

### ISSUE THREAD

**Issue by jrobertson-insite** [belav/csharpier#141]
It seems that understanding why a line was formatted a given way is a guess and check process. Is there a way to write out a {filename}.cs.debug file that would show in comments (or otherwise) what rule(s) caused a line to change?

**Comment by belav** [comment]
The typical process I follow when debugging formatting.

- Format code using the playground
- Use the AST tab to determine what type of CSharpSyntaxNode represents the code I'm trying to debug
  - Optionally use SharbLab instead. It maps code to AST
- Starting place to look in code is typically Printer/[CSharpSyntaxNode] or going forward SyntaxPrinter/SyntaxNodePrinters/[CSharpSyntaxNode]
- Use the Doc tab to see what kind of Doc elements are being used to format the code.

The thing that would help me the most, would be if the playground could map between code, AST and doc. Similar to what SharbLab does
![image](https://user-images.githubusercontent.com/3606529/116100615-b8181280-a672-11eb-9347-747098e77355.png)

But I'm not sure if it is worth the effort it would take.
