### ISSUE TITLE
Formatting deletes `unsafe` modifier

### ISSUE THREAD

**Issue by Saancreed** [belav/csharpier#1416]
**Input:**

```cs
using unsafe NvapiQueryInterface = delegate* unmanaged[Cdecl]<uint, nint>;
```

**Output:**

```cs
using NvapiQueryInterface = delegate* unmanaged[Cdecl]<uint, nint>;
```

**Expected behavior:**

`unsafe` keyword should have been preserved, as removing it leads to a compilation error:

> Pointers and fixed size buffers may only be used in an unsafe context (CS0214)

CSharpier version is 0.30.3, and it reports `Error ./Program.cs - Failed syntax tree validation.` when ran from the CLI.

**Comment by belav** [comment]
Thanks for the report! I'll cut a release for this now, it should be out shortly.

**Comment by Saancreed** [comment]
That was blazingly fast, thank you! :heart:
