### ISSUE TITLE
To SpaceBrace or not to SpaceBrace

### ISSUE THREAD

**Issue by belav** [belav/csharpier#144]
This is the SpaceBrace
![image](https://user-images.githubusercontent.com/3606529/115998837-ce5c9a80-a5ae-11eb-9923-4d91b11db0bb.png)

It is not how c# has really been formatted.
It is how prettier formats js/ts.
It may have not been used before prettier.
Should CSharpier not use SpaceBrace?

See https://github.com/belav/csharpier/issues/34 for some discussion

**Comment by belav** [comment]
After thing to consider. How will generic methods print? This is their current state, which will change.
```c#
        public static Doc Print<T>(
            SeparatedSyntaxList<T> list,
            Func<T, Doc> printFunc,
            Doc afterSeparator
        )
            where T : SyntaxNode {
```

**Comment by respel** [comment]
I think it's worthwhile to stick with what the community is doing, especially in cases where the mandate is clear. And this is one of them.  

For the generic method, I think we can put the constraint on the same line as the parameter end bracket.
```csharp
public static Doc Print<T>(
    SeparatedSyntaxList<T> list,
    Func<T, Doc> printFunc,
    Doc afterSeparator
) where T : SyntaxNode 
{
    var docs = new List<Doc>();
    return docs;
}
```

**Comment by belav** [comment]
We've settled on SpaceBrace and have generic methods formatting well. I'm going to close this.
