### ISSUE TITLE
Configurable option for splitting expression-bodied methods

### ISSUE THREAD

**Issue by YandyZaldivar** [belav/csharpier#187]
When formatting I want to keep this:
```
string MyMethod() =>
    "method";
```
 
Instead of:
`string MyMethod() => "method";`

Example in .csharpierrc:
`"splitExpressionBodiedMethods": true`

**default: false**

**Comment by belav** [comment]
I appreciate the interest in CSharpier but at this point there are no plans to add any configuration options of this nature. See https://prettier.io/docs/en/option-philosophy.html for a good write up why we plan to keep formatting options out of CSharpier.

**Comment by shocklateboy92** [comment]
Hey, as @belav explained we don't plan on adding these kinds of options. 
However, (at least in this early stage) the formatting style itself _is_ open for debate. :smile: 

> I am not very familiar with prettier and js/ts but I think that is not an issue in those languages because you don't have expression-bodied methods

Point of pedantry I suppose, but that isn't true. :smirk:  They're called arrow functions in Js/Ts:
```typescript
export default (arg: string) => "prefix " + arg + "suffix";
```

However, getting back to the actual discussion:
```cs
public void Serialize(string value) => InternalSerialize(value);

public void Serialize(int value) => InternalSerialize(value.ToString());

public void Serialize(long value) => InternalSerialize(value.ToString());

public void Serialize(double value) => InternalSerialize(value.ToString());

public void Serialize(ReadOnlySpan<byte> value) =>
    InternalSerialize(Encoding.Utf8.GetString(value));
```

Quickly skimming down the page it's very easy to grasp which part of the expression belongs to what because of the indentation and the blank line. Forcing a line break on each of those would increase "consistency" I suppose, but I don't think it will increase readability significantly.

Thus, my personal vote is *no*.

**Comment by belav** [comment]
> Thanks for the answer, I think that should be specified more explicitly in the readme.

Definitely, I'll get it updated shortly

>I am not very familiar with prettier and js/ts but I think that is not an issue in those languages because you don't have expression-bodied methods.

My experience with prettier (and also with dogfooding csharpier) - you get used to the breaking and non-breaking way statements can appear.



Right now variable declarations only break if they get too long. If we start to break short expression bodied methods, then shouldn't variable declarations always break too?

```c#
var x =
    1;

var someReallyLongName =
    "someReallyLongValueThatBreaks11111111111111111111111111111111";
```

So my personal vote is no as well. 

Not sure if I want to open a potential can of worms.... but what about breaking things this way? It seems like the arguments for breaking before a binary operator could also apply here.
```c#
public void Serialize(ReadOnlySpan<byte> value)
    => InternalSerialize(Encoding.Utf8.GetString(value));
    
var someReallyLongName
    = "someReallyLongValueThatBreaks11111111111111111111111111111111";
```

**Comment by YandyZaldivar** [comment]
My proposal was because this is how I differentiate members in a class, lets say fields/properties in one line whenever possible and expression bodied methods always in at least two lines, so visually I can recognize quickly if it is a field/property or a method.

I see that this can lead to other debate and I totally agree in focus on the goal of an opinionated formatter. We can always run our own formatting layers on top of this.

I am closing this, thank you all for sharing your perspective, this is an awesome library!
