### ISSUE TITLE
Formatting of implemented classes/interfaces

### ISSUE THREAD

**Issue by respel** [belav/csharpier#189]
```csharp
//Is
public class AClass
    : AReallyLongBuilder<BuilderType>,
        IAnotherReallyBuilder<AnotherType> { }

//ShouldBe
public class AClass
    : AReallyLongBuilder<BuilderType>, IAnotherReallyBuilder<AnotherType> { }

OR 

public class AClass
    : AReallyLongBuilder<BuilderType>, 
      IAnotherReallyBuilder<AnotherType> { }
```

**Comment by belav** [comment]
I believe there is a one related issue but I'm not sure that it covered a class that implemented more than one thing.

**Comment by belav** [comment]
Related, but not exactly the same - https://github.com/belav/csharpier/issues/101

**Comment by respel** [comment]
I'm not really sure if it's actually a bug since [`prettier`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgA1C4APeKAEwGdCBBAJTlwBs2BPAGWgHMAQgFdUbalgA8w0eMwAVTgAc4APgA0AHSiEdunQEkGUCDAAWWFuy7SxkoyfPylqwsEIBfEGpARFMVNC0yKC4mJgQAO4ACqEIQSjsEbicQd4ARpj4ANZwMADKivjofMgwmEJw3nAAtmlw1OLU3LhQfEK4fHAAYhCY1bgw-q3IILhCMBBeIKYw1WwA6qao8LSFBHlxy6gAbsucI2C0qWhQtFgwUZl8-ch4bGfeAFa05AKZYDn5uNVw3Ohwt3YDxAz3IeWKbDgAEUhCYAUg7sDCpgzpgRmlcHU2FNFJh0DB5qhqGZkAAOAAM3lxEDO80yihGuLgqO2AO8AEdYfBLr54qNaABaKBwer1KaYOCc1ASy4dG4IoGVEBnaqoUrlJW0CHQrnwxFKmCYwnE0zIABM3jKuFExQAwhBqvKQMyAKxTIRnOSY+L67zbCr6GgIfJgPF+IzUPIwTiQwH3ODudxAA) and [`google-java-format`](https://github.com/google/google-java-format/blob/5104d0b27888f3bfab7113f5606374cda5632102/core/src/test/resources/com/google/googlejavaformat/java/testdata/B28066276.output) both do something similar. The only difference is that they have an `extends` keyword instead of a colon so it looks less weird.

I think we should close this one.

**Comment by belav** [comment]
I'd still love to get this looking less weird even if prettier` currently doesn't, but I definitely consider it a low priority.

I tried out [prettier-java](https://github.com/jhipster/prettier-java) and this is how they format it.
```java
class B28066276 {

  class A
    extends S
    implements
      I________________,
      I________________,
      I________________,
      I________________ {}

  interface B
    extends
      I________________,
      I________________,
      I________________,
      I________________ {}
}
```
Which I think would look really weird in c#
```c#
public class AClass
    : 
        AReallyLongBuilder<BuilderType>, 
        IAnotherReallyBuilder<AnotherType> { }
```
Maybe this, which is a little better.
```c#
public class AClass : 
    AReallyLongBuilder<BuilderType>, 
    IAnotherReallyBuilder<AnotherType> { }
```
