### ISSUE TITLE
Templated declarations break at weird points

### ISSUE THREAD

**Issue by respel** [belav/csharpier#190]
```csharp
//Is
public class X
{
    public static readonly Dictionary<string,
        ALongType> ClientToDefaultCoordinates = new Dictionary<string,
        ALongType>();
}
//ShouldBe
//???
```

Not sure what the end result should be, but the current formatting looks a bit weird.

**Comment by belav** [comment]
Yeah this definitely should be addressed somehow. It may be a duplicate but I can't validate that until I'm at a computer.

**Comment by belav** [comment]
This appears to be a duplicate of https://github.com/belav/csharpier/issues/47

**Comment by respel** [comment]
Duplicate of #47
