### ISSUE TITLE
Loops without braces

### ISSUE THREAD

**Issue by shocklateboy92** [belav/csharpier#202]
I had foreach loop in my code without braces 
```cs
foreach (var c in word.Original)
    switch (c)
    {
        case '(':
        case '（':
            bracketCount++;
            break;
        case ')':
        case '）':
            bracketCount--;
            break;
    }
```

and csharpier did this to it:
```cs
foreach (var c in word.Original)switch (c)
{
    case '(':
    case '（':
        bracketCount++;
        break;
    case ')':
    case '）':
        bracketCount--;
        break;
}
```

Should we make csharpier deal with conditions/loops without braces? Or should we just have it add braces automatically?

**Comment by belav** [comment]
I see the options as

1. Add braces automatically
2. Add an option to add braces automatically - which kind of goes against the no options philosophy
3. Don't add braces - for people that do want to enforce braces they could use style cop and it looks like this is what prettier does

Prettier has had requests to add an option https://github.com/prettier/prettier/issues/7659
Which lead me to https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about

> Prettier only prints code. It does not transform it. This is to limit the scope of Prettier. Let’s focus on the printing and do it really well!
> Here are a few examples of things that are out of scope for Prettier:
> - Adding/removing {} and return where they are optional.

Which has convinced me that not adding braces is probably the way to go. Also if we start adding braces then the CSharpier validation process needs to take that into account or it will report the new braces as a failure.

**Comment by shocklateboy92** [comment]
Okay, in that case this bug should just track printing if/for blocks
without braces properly.
