### ISSUE TITLE
Better generic ObjectCreationExpressionSyntax

### ISSUE THREAD

**Issue by belav** [belav/csharpier#239]
The current formatting is
```c#
    public static Dictionary<Type, string> PropertiesByType = new Dictionary<
        Type,
        string
    >();
```
I think it would be possible to format like this, but this may require conditionalGroups. See https://github.com/belav/csharpier/issues/7
```c#
    public static Dictionary<Type, string> PropertiesByType =
        new Dictionary<Type, string();
```

**Comment by shocklateboy92** [comment]
I don't get why conditional groups would be needed. I thought the logic in doc for nested groups is to try breaking the outer groups before inner ones.

So if we change the printer to something loosely resembling:
```cs
Doc.Group(
    Node.Print(/* the stuff on the left */),
    "=",
    Node.Print(/* the stuff on the right */)
)
```
Would we not get the desired effect?
Same goes for #250

**Comment by belav** [comment]
This appears to have been resolved at some point
