### ISSUE TITLE
Foreach Statement Formatting

### ISSUE THREAD

**Issue by belav** [belav/csharpier#25]
This should break somewhere
```c#
foreach(var someReallyLongNameYeah in this.SomeOtherReallyLongNameToGetStuff()) {
    break;
}

**Comment by ryanavogel** [comment]
@belav where else do you want it to break other than after the closing paren? prettier doesn't do anything more than that.
                                                                                                                                              <--- 80 characters is at this 'a'
`for (const thisDoesNotMakeSenseButItsAReallyLongVariableName in someReallyLongNameForAnObjectThatIsWayTooLong) {
    console.log(`${property}: ${object[property]}`);
}`

**Comment by belav** [comment]
I was thinking break something like this.
```c#
foreach (var thisDoesNotMakeSenseButItsAReallyLongVariableName
    in someReallyLongNameForAnObjectThatIsWayTooLong)
{
    break;
}
```
I'm guessing foreach's will almost never need to break like this, but it's a good way to learn how to get something to format.
I think generally a long foreach would be because of something like this, and the method call breaking would make sure the line doesn't get too long. If doing this doesn't play nice with methods we could just leave it as is.
```c#
foreach (var customer in this.UnitOfWork.GetRepository<Customer>()
    .GetTable()
    .Where(o => o.Name == "yeah")
    .OrderBy(o => o.Name))
```

**Comment by belav** [comment]
Breaking before the in makes the method chained foreach's uglier, and those are gonna be way more common.
