### ISSUE TITLE
Obnoxious Edge Cases

### ISSUE THREAD

**Issue by belav** [belav/csharpier#272]
There are a number of obnoxious edge cases that we should address. They were added as tests so that when formatting changes that affects them, we can see how they evolve and hopefully address them somewhat with related bugs.

At some later date we should try to get them cleaned up. Hopefully that will just happen.

**Comment by shocklateboy92** [comment]
Adding a link to [the file](https://github.com/belav/csharpier/blob/a4ba7787f00cb63e90bd821770860df82262ab37/Src/CSharpier.Tests/TestFiles/ObnoxiousEdgeCases/ObnoxiousEdgeCases.cst), for easy reference.
