### ISSUE TITLE
Blocks inside of other blocks are getting an extra new line.

### ISSUE THREAD

**Issue by respel** [belav/csharpier#316]
```csharp
//Is
switch (x)
{
    case 1:

        {
            return 1;
        }
        break;
}

//ShouldBe
switch (x)
{
    case 1:
        {
            return 1;
        }
        break;
}
              
```

There's an extra line when there's a scope block introduced. 
[Reference](https://github.com/belav/Newtonsoft.Json/blob/93121e09c167763f02732518b8bfe7047e0b274b/Src/Newtonsoft.Json/Bson/BsonBinaryWriter.cs#L76)

**Comment by belav** [comment]
It looks like this is actually a problem with block. I think this example makes it more clear what is going on
```
        switch (x)
        {
            case 1:
            {

                {
                    return 1;
                }
                break;
            }
        }
```
It also happens here
```
    void MethodName()
    {

        {
            var x = 1;
        }
    }
```

We may be assuming that a block always needs to start with a line, which causes a double line in these cases.

**Comment by respel** [comment]
@belav I see. You're completely right. I've updated the title to reflect that
