### ISSUE TITLE
Long throw statement not wrapping

### ISSUE THREAD

**Issue by respel** [belav/csharpier#318]
[Link](https://github.com/belav/Newtonsoft.Json/blob/93121e09c167763f02732518b8bfe7047e0b274b/Src/Newtonsoft.Json/Converters/BinaryConverter.cs#L176)

I wasn't able to create a minimal example but the line is too long and should have been wrapped.

**Comment by belav** [comment]
.assign

**Comment by belav** [comment]
This is because basically the whole class inside of `#if HAVE_LINQ || HAVE_ADO_NET`

We don't currently support formatting code inside of an `#if` because of #15 

I'm closing this as a duplicate.
