### ISSUE TITLE
If Statement with long expression

### ISSUE THREAD

**Issue by belav** [belav/csharpier#34]
Currently when an if statement has a long expression, it formats like
```c#
if (
    !this.model.TranslatableFields.TryGetValue(
        fieldName,
        out var dictionary
    )
)
{
    return;
}
```
I think it should do this
```c#
if (
    !this.model.TranslatableFields.TryGetValue(
        fieldName,
        out var dictionary
    )
) {
    return;
}

if (shortStatement)
{
    return;
}
```
or
```c#
if (
    !this.model.TranslatableFields.TryGetValue(
        fieldName,
        out var dictionary
    ))
{
    return;
}

if (shortStatement)
{
    return;
}
```

This applies to other syntax nodes, like for loops and while loops.

**Comment by shocklateboy92** [comment]
Hmmm. I'm _definitely_ not a fan of # 3. # 2 might make sense if we want to make it consistent with things like constructors or long method defintions:
```C#
public Constructor(
    Type arg1,
    Type arg2
) {
    // logic
}

**Comment by belav** [comment]
I made #2 work, which I'm going to call SpaceBrace (vs NewLineBrace).
I made WhileStatements, IfStatements, ForEachStatements and UsingStatements all use SpaceBrace.
There are a number of other node's that have a block syntax that could also use SpaceBrace.

I see two options
1. Format everything that has a block syntax using SpaceBrace. Which means in the example below, the MethodDeclaration would be changing.
2. Format everything that has the potential to be deeply nested using SpaceBrace, everything else using NewLineBrace. In the code below, the MethodDeclaration can only have parameters, it can't really be any deeper, so it would stay NewLineBrace.

I think I'm leaning towards option 1, because then things are consistent. But I'm not opposed to option 2 either.

```c#
    public void LongMethodNameForceLineBreak(
        string oneoneoneoneoneoneoneoneone,
        string twotwotwotwotwotwotwotwo,
        string threethreethreethreethreethree)
    {
        if (
            longStatementName
            && longerStatementName
            && evenLongerStatementName
            && superLongStatementName
        ) {
            return;
        }
    }
```

**Comment by belav** [comment]
After working on https://github.com/belav/csharpier/issues/58 I'm thinking we go all in on SpaceBrace.
In order to print Lambda methods like this, we need a SoftLine before the close paren. If we wanted to use NewLineBrace we'd have to add extra logic to decide when that SoftLine should be added.
```c#
const doSomething = (
  jasdjklfasjkldflajskdflkasdlfjkasdf,
  jalsdfkasdlkfalksflksdf,
  kjladslkfasjfkasdfl
) => doSomethingElse();
```

**Comment by jrobertson-insite** [comment]
This is closed... but the spacebrace in all cases as seen in the screenshot below is seemingly not the way the vast majority of C# is formatted in my experience.

![image](https://user-images.githubusercontent.com/16560965/115965344-69da0680-a4ee-11eb-9a6e-316c673ee61f.png)

**Comment by svermeulen** [comment]
Yeah, I think going all on space brace may end up being a mistake.  Opinionated code formatters should ideally just follow whatever the consensus is for the community of that language at large, which I don't think is space brace.  The style used in other languages like JS should not really be a factor here
