### ISSUE TITLE
BinaryExpression Grouping

### ISSUE THREAD

**Issue by belav** [belav/csharpier#37]
Take this example
```c#
var longNameForcesLineBreakYeahLongName =
    someValue == someOtherValue && x == 7;
```
The && is the root BinaryExpression, which is a LogicalAnd
The left and right of it are EqualsExpression.
CSharpier should group the LogicalAnd, but if it groups every binary Expression than the following doesn't format correctly.
```c#
if (
    longStatementName
    && longerStatementName
    && evenLongerStatementName
    && superLongStatementName
) { }
```
Which is basically a tree of BinaryExpressions where the Left is LogicalAnd BinaryExpression and the Right is IdentifierName.
This may require flattening out BinaryExpressions and conditionally grouping them based on what operation they are performing.

See prettier/src/language-js/print/binaryish.js for all the logic that goes into making this work for js

**Comment by belav** [comment]
This is also related
```c#
    return value == null
    || string.IsNullOrEmpty(value.Trim());
// should be
    return value == null
        || string.IsNullOrEmpty(value.Trim());
```

**Comment by belav** [comment]
This was partially addressed in https://github.com/belav/csharpier/pull/84 but requires a lot more work

**Comment by belav** [comment]
this looks weird
```c#
        if (
            trivia.Kind() == SyntaxKind.SingleLineCommentTrivia
            || trivia.Kind()
            == SyntaxKind.SingleLineDocumentationCommentTrivia1111111
        ) { }
```

**Comment by belav** [comment]
See also
```c#
        protected override bool IsBinaryLike(ExpressionSyntax node) =>
            node is BinaryExpressionSyntax
            || node
                is IsPatternExpressionSyntax isPattern
            && isPattern.Pattern is ConstantPatternSyntax;
```

**Comment by divyanshshukla13** [comment]
Related
```csharp
while (
  // stop if we have reached the end of the token being read
  initialDepth - 1 <
    reader.Depth - (JsonTokenUtils.IsEndToken(reader.TokenType) ? 1 : 0) &&
  writeChildren &&
  reader.Read()
);
```

https://github.com/belav/Newtonsoft.Json/blob/397e45649325788b5ea299be3ca5303b86eeaf9b/Src/Newtonsoft.Json/JsonWriter.cs#L773

**Comment by respel** [comment]
See also
```csharp
if (
    query
    && (currentChar == '='
    || currentChar == '<'
    || currentChar == '!'
    || currentChar == '>'
    || currentChar == '|'
    || currentChar == '&')
) {
    ended = true;
}
```

The current alignment leads you to believe that the && and || operators are chained but they aren't really. We should do some kind of nesting here.

**Comment by belav** [comment]
Make sure to handle the test case in SwitchExpression that isn't indenting.
