### ISSUE TITLE
Better error handling when given a csproj or sln file

### ISSUE THREAD

**Issue by svermeulen** [belav/csharpier#398]
When I attempted to use this, I misread the command line instructions and passed in a `.sln` file or a `.csproj` file because this is how the [dotnet formatter](https://github.com/dotnet/format) works.  This resulted in this output:

```
+dotnet csharpier Foo.sln
/Foo.sln                                                                                                                 - failed to compile
total time:                                                                          243ms
Total files:                                                                           1
Failed syntax tree validation:                                                         0
Threw exceptions while formatting:                                                     0
files that threw exceptions while validating syntax tree:                              0
```

Which led me to believe that the sln file was not compiling, and not that I was supplying an invalid file.  I understand now how it is meant to work, but wanted to just suggest that this error message be improved.   When not given a `.cs` file or a directory, can it print out clearer instructions?

EDIT:  Or, alternatively, actually process csproj / sln files and format all the C# scripts inside them

**Comment by belav** [comment]
I like the idea of allowing someone to pass a csproj/sln file, I created #399 for adding support for it.
Even with that implemented, if someone passes a path to csharpier that it can't format it should definitely let the user know.
