### ISSUE TITLE
What's up with the `CSharpier.Parser` directory?

### ISSUE THREAD

**Issue by shocklateboy92** [belav/csharpier#44]
While trying to get my development environment going and all the tests running/passing, I `SyntaxNodeJsonWriterGenerator` tries to write to a file in a `CSharpier.Parser` directory:
https://github.com/belav/csharpier/blob/8011144d238de869f2531e2a830665b65947f385/Src/Worker/SyntaxNodeJsonWriterGenerator.cs#L30

which of course fails, because that directory doesn't exist.
I noticed that there's a version of `SyntaxNodeJsonWriter.generated.cs` in `CSharpier` directory, so I tried updating the path. However, the generated file seems to be drastically different than the one committed, and now generates a tonne of build errors.

Could you take a look at what's going on with that? I'm hoping it's a simple fix like a missing `using` in the generated file.

**Comment by belav** [comment]
I'm fairly positive SyntaxNodeJsonWriterGenerator is left over from when csharpier was a prettier plugin.
Basically all of the "tests" in Worker are for code generation. I've had bad experiences with tt files and wasn't aware of source generators until recently. From a quick glance, the only one that may be needed during development is GeneratePrinterSwitch if a new node type is added to CSharpier/Printer/*.cs
I can get these cleaned up this weekend. I'll probably just add [Ignore] to any that stick around to avoid any future confusion.

**Comment by shocklateboy92** [comment]
Cool. I'll continue waddling through some code. Looking at the commit history, it looks like you recently put in a decent amount of work to get it to build/run on Linux. Just want to take a moment to say kudos because all my dev machines run Arch Linux. :smirk: 

Also, shall we create a chatroom/channel for this project? I feel it'll be much quicker for me to get up to speed over IM than going back and forth through bugs. :smile: 
I like [matrix](https://matrix.org/) the best because the whole thing is open source and distributed, but Discord or Slack will also suffice. Let me know what you decide.

**Comment by belav** [comment]
Yeah I finally set up a github action to run the unit tests automatically after a couple rounds of breaking stuff without realizing it and it made sense to do those in linux as a way to ensure things would probably work on linux.
I think I'd prefer discord just so that I don't have to install and pay attention to another chat application. I set up one at https://discord.gg/HVzbpGKZ
