### ISSUE TITLE
Formatting of boolean expressions does not match Prettier

### ISSUE THREAD

**Issue by Sti2nd** [belav/csharpier#442]
In csharpier playground the operators in boolean expressions are put first, is this on purpose or a bug?

Csharpier:

```c#
if (
    updated.City != current.City
    || updated.Address != current.Address
    || updated.Country != current.Country
    || updated.Floor != current.Floor
    || updated.VisitorInstructions != current.VisitorInstructions
    || updated.ZipCode != current.ZipCode
) {
    return false;
}
```

Prettier:

```js
if (
  updated.City != current.City ||
  updated.Address != current.Address ||
  updated.Country != current.Country ||
  updated.Floor != current.Floor ||
  updated.VisitorInstructions != current.VisitorInstructions ||
  updated.ZipCode != current.ZipCode
) {
  return false;
}
```

**Comment by belav** [comment]
This is on purpose. There are some good arguments that operators at the beginning of the line are easier to read and they result in smaller diffs when adding new conditions. - [1](https://github.com/airbnb/javascript#control-statements), [2](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator)
Prettier has an open issue about switching to operators at the beginning, but it sounds like they are waiting until the next major version to make the change - https://github.com/prettier/prettier/issues/3806

**Comment by Sti2nd** [comment]
Makes sense! Thanks for informational the links 😊
