### ISSUE TITLE
Using csharpier with a raw SourceText as source

### ISSUE THREAD

**Issue by TwentyFourMinutes** [belav/csharpier#470]
I am currently writing some Source Generators and I am emitting the source from raw SyntaxTrees through the SyntaxFactory API, would there be any way that I can throw the SourceText at csharpier and get a SourceText/string back? 

I personally would love to have this feature as it would allow for the Source Generator consumer to have way more readable code as the one that NormalizeWhitespace emits on its own.

**Comment by TwentyFourMinutes** [comment]
Hey that is awesome, I'll give it a shot once available!

**Comment by belav** [comment]
CSharpier.Core is available as of five minutes ago, see https://github.com/belav/csharpier/blob/master/README.md#programmatically-formatting-code

**Comment by TwentyFourMinutes** [comment]
So, I sadly got to it only by now. As I am trying to consume the library I am limited to .NET Standard 2.0, which currently `CSharpier.Core` does not support. Any chance that this will happen? Or are you relying on anything >= .NET 5 specific?

**Comment by belav** [comment]
CSharpier uses some c# features that aren't available with .net standard 2.0, but it appears to be possible to shim them in.

I haven't tested the .netstandard 2.0 dll yet, but it at least compiles.

https://github.com/belav/csharpier/pull/619

**Comment by TwentyFourMinutes** [comment]
I can give it a shot if you want me to :)
