### ISSUE TITLE
With only .NET 6 installed, it gives an error  'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.

### ISSUE THREAD

**Issue by Ciantic** [belav/csharpier#478]
I removed all other runtimes but .NET 6, because they were acting funny, but now it looks like csharpier won't work:

```
C:\Source\dotNET\TestGraphqlHotchocolate>dotnet csharpier .
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64
```

I probably go just get the older runtimes too, but if someone is new to .NET using latest 6.0, they would get the above error too, since 5.0 is not bundled with it.

**Comment by belav** [comment]
The next version of csharpier will support .net 6 and c# 10. If all goes well it will be out tomorrow. I meant to have it out at the same time as .net 6 became official but am a bit behind.
Did you uninstall .net 5 after installing csharpier? I assume .net would complain if you tried to install a tool that only worked with .net 5 if you only have 
.net 6 installed.

**Comment by Ciantic** [comment]
I re-installed .NET 5 SDK and csharpie ran in .NET 6 project just fine. I guess the AST hasn't changed, if this works like prettier, all it needs is same AST.

**Comment by belav** [comment]
CSharpier uses https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/ for the AST, which only requires .net standard 2.0. But CSharpier is published as a dotnet tool, which must target .net 5/6 or .net core.
0.11.0 was released earlier today, which should work with just .net6 installed.
