### ISSUE TITLE
Can't run CLI if current directory contains multiple project files

### ISSUE THREAD

**Issue by acornellier** [belav/csharpier#489]
I'm running `dotnet csharpier` that contains multiple project files and it throws an error. I'm on a Mac. But if there are no project files at all, it works fine, so it clearly doesn't rely on them existing.

```
❯ dotnet csharpier
Specify which project file to use because this '/Users/...' contains more than one project file.
```

**Comment by belav** [comment]
CSharpier requires passing a directory or file, it doesn't work in the context of a project or a solution [yet](#399). If you don't supply a path, it should error with the following message.
```
directoryOrFile is required when not piping stdin to CSharpier
```
So I am not sure where the message you are seeing is coming from. I tried out `dotnet csharpier` and `dotnet csharpier .` in a directory that had multiple csprojs and one that contained multiple solutions and was not able to reproduce what you saw.

The error you are seeing shows up in google for other dotnet tools like EF, CsprojToVs2017 and sonarscanner, so I am wondering if it is coming from the dotnet cli itself. The sonarscanner issue is very recent - https://github.com/SonarSource/sonar-scanner-msbuild/issues/1103
