### ISSUE TITLE
Extensions do not take into account solution version of csharpier

### ISSUE THREAD

**Issue by belav** [belav/csharpier#493]
Currently the vscode extension runs `dotnet cshapier` outside of the context of where the file lives. This could result in it not formatting code the way it should

1. Install version 0.11.1 globally
2. Install version 0.12.0 in a solution
3. Formatting a file from that solution in VSCode should use the 0.12.0 version of csharpier.

When we initialize the vscode extension, we do it outside of any kind of file/folder context.
We need some way to figure out what version of csharpier a file should be formatted with, and load up a new csharpier process if the version does not match.

**Comment by oraziomarano1** [comment]
Proviamo anche questo augurando che funzioni
