### ISSUE TITLE
VSCode extension with csharpier 0.12.0 corrupts the file (cutting it)

### ISSUE THREAD

**Issue by Ciantic** [belav/csharpier#500]
Here is a screencap what it does, it cuts the file from the end:

https://user-images.githubusercontent.com/64731/144029050-1cc0732f-5bb3-4cf8-ab1e-2c9c6c14302c.mp4

**Comment by belav** [comment]
Sorry about that, all my tests were with short files. This was easily reproduced with a slightly longer file.
1.0.2 fixes the problem and will be available shortly.
