### ISSUE TITLE
Encoding During Format On Save

### ISSUE THREAD

**Issue by dacarmr** [belav/csharpier#545]
Firstly, thank you so much for this project.

I am part of an international team and when formatting utf8 files with unicode chars the chars get replaced with "?".
In our .editorconfig  we have charset=utf-8
Then in our cs file we have this line:

```csharp

private const char test = '。';

```

After saving the file it becomes:

```csharp

private const char test = '?';

```

For now I can use '\u' but sometimes we have Japanese text in files so we do not want those to break.

Sorry I left out a lot of needed info...

Using VS2022, global install + extension.
Using command "dotnet csharpier ." doesn't cause this issue.
"Reformat with CSHarpier on Save" = true causes the issue on save.

Thanks.

**Comment by belav** [comment]
Is there a public repo that I could use to recreate the issue? The unicode character formats as expected when using csharpier.com and I won't have access to a computer to test it properly until next week. In theory csharpier is supposed to leave files in the same encoding that it finds them.

Also if you end up trying it yourself on csharpier.... It seems like the cert has just expired.

**Comment by dacarmr** [comment]
I'll try create a public repo over the weekend. On csharpier it works correctly.

**Comment by dacarmr** [comment]
I've uploaded a sample [Here](https://github.com/dacarmr/CSharpierEncodingTest)
I've updated the original comment, this appears to be the vs2022 extension issue with format on save.

**Comment by belav** [comment]
I think I should be able to reproduce it now and get a fix out pretty quickly next week. My guess is that properly means determining the encoding of the file earlier, and then reading the output using that encoding.

**Comment by belav** [comment]
The fix for this is mostly ready to go, I just need to do some more testing. It will require a new version of csharpier. And a new version of the VS and rider extensions.

**Comment by belav** [comment]
This is resolved with csharpier 0.14.0 + 1.0.1 of the VS extension or 1.0.4 or the rider extension. The rider extension requires jetbrains to manually approve each update so it may not be out for a couple of days.

**Comment by dacarmr** [comment]
Thank you so much.

**Comment by belav** [comment]
You are welcome!
