### ISSUE TITLE
Multiline comments are not properly indented.

### ISSUE THREAD

**Issue by dlech** [belav/csharpier#580]
I was hoping to use csharpier on a code base that currently uses 2 space indents. One thing I noticed right away is that the indentation of multiline comments is not handled correctly. Only the first line in indented and the rest of the lines remain where they were. This applies to both xml doc comments and C-style comments.

Actual:

![image](https://user-images.githubusercontent.com/963645/151716371-c887394b-33f3-4101-b172-6e1a24a81fc8.png)

Should be:

![image](https://user-images.githubusercontent.com/963645/151716416-c43128b8-597b-4ce7-90cc-665c3ef4911a.png)

Actual:

![image](https://user-images.githubusercontent.com/963645/151716476-bccd590e-8578-45cc-993e-da21b1da6af8.png)

Should be:

![image](https://user-images.githubusercontent.com/963645/151716556-d85a1f1a-987e-486b-b0d8-354104817403.png)

As a workaround, I used `dotnet format` first, then `dotnet csharpier`.

**Comment by belav** [comment]
This is working for `///` style comments in 0.15.0. My solution for `/*` style comments was not playing nice with commented out code and I haven't found a good solution yet. I created #606 to address it.
