### ISSUE TITLE
Csharpier .editorconfig

### ISSUE THREAD

**Issue by GravlLift** [belav/csharpier#630]
I'm trying to use both dotnet-format and csharpier on a project, as there are some fixes that dotnet format can provide that csharpier doesn't handle and vice versa. However, I'd like dotnet format to defer to csharpier's rules whenever there's any crossover.

Is it possible that we could get an .editorconfig file that describes csharpier's current rules as closely as possible?

**Comment by belav** [comment]
It is possible to run dotnet-format from the command line without changing whitespace and from my understanding (without actually using it in the real world) that would avoid any potential conflicts.  See https://csharpier.com/docs/IntegratingWithLinters

If there are situations where dotnet-format runs and it isn't possible to pass it the options to avoid formatting whitespace then I think it makes sense to figure out the .editorconfig that gets it as close as possible.

**Comment by GravlLift** [comment]
Yeah, there's not really any conflicts if using the commands (just run dotnet-format first, then run csharpier second, second command "wins"). However there are many VS2022 suggestions that pop up based on a solution's .editorconfig file, and it'd be good if I could figure out how to get those to align with csharpier's rules.

**Comment by belav** [comment]
That makes sense. I feel the need to address every suggestion that rider makes, so I can relate.

**Comment by belav** [comment]
I started with just this in an `.editorconfig`, and `dotnet format whitespace` doesn't have a lot of changes. 
```
indent_style = space
indent_size = 4
trim_trailing_whitespace = true
insert_final_newline = true
```

The only two differences, at least in the csharpier codebase, are indentation inside a switch and indentation on pattern matching.

However it is completely happy with the places where csharpier indents 2 spaces. It doesn't seem to care at all what kind of indentation is used in a conditional like this, nor does visual studio.
```c#
return true
  ? false
      ? 1
      : 3
  : 4;
```

If I use riders code cleanup there are a lot more differences. Rider does have quite a few custom properties that could be tweaked to get it closer. This is the only one I tracked down so far.
```
resharper_csharp_empty_block_style = together_same_line
```

**Comment by Jogai** [comment]
Why is csharpier not using the .editorconfig? Its basically an industry standard now and microsoft recommends it: https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022 and supports a fair amount of specific rules: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options

**Comment by belav** [comment]
The only option CSharpier currently supports is `printWidth`. I could be convinced that it makes sense to read the `max_line_length` value from an editorconfig in place of `printWidth` but no one has asked for it. The only reason I could see not doing it is because it may be a little weird to "support" an editorconfig but completely disregard other formatting properties that are in the file.

**Comment by Jogai** [comment]
Ah ok, make sense for an 'opinionated' formatter.

**Comment by sethreno** [comment]
+1 for supporting max_line_length

**Comment by justinmchase** [comment]
I too am already using the built in dotnet format tool but it straight up sucks at whitespace formatting at the moment. I'd like to use this tool to get it the rest of the way there and the only CSharpier config options I'd like to use are already in the `.editorconfig` (the ones already mentioned in this thread above). 

So really if this tool were to look into the .editorconfig for the default values for these settings it would just work out of the box. If the `.csharpierrc` file happens to be there it could win over the `.editorconfig` but by default it would work as expected for most people already using the dotnet formatter.

**Comment by sethreno** [comment]
@belav Any objection to a PR for this? Was thinking of reading the following from the top level .editorconfig if .charpierrc doesn't exist:

* max_line_length = printWidth
* indent_style (tab|space) = useTabs (true|false)
* indent_size = tabWidth

My plan would be to add the new code around this line:
https://github.com/belav/csharpier/blob/7cea674cb8f34fe11b66f1e741ca907180d6e29f/Src/CSharpier.Cli/ConfigurationFileOptions.cs#L74

**Comment by belav** [comment]
@sethreno none at all, I just haven't had the time to get to this.

That looks like the proper place, and then some tests to cover different situations in https://github.com/belav/csharpier/blob/master/Src/CSharpier.Tests/ConfigurationFileOptionsTests.cs is probably all that is needed.

**Comment by JWess** [comment]
> @belav Any objection to a PR for this? Was thinking of reading the following from the top level .editorconfig if .charpierrc doesn't exist:
> 
> * max_line_length = printWidth
> * indent_style (tab|space) = useTabs (true|false)
> * indent_size = tabWidth
> 
> My plan would be to add the new code around this line:
> 
> https://github.com/belav/csharpier/blob/7cea674cb8f34fe11b66f1e741ca907180d6e29f/Src/CSharpier.Cli/ConfigurationFileOptions.cs#L74

I'm a big fan of this idea. I arrived here because I changed `max_line_length` in my .editorconfig and was surprised when nothing was affected.
