### ISSUE TITLE
VS Code Extension - Unsaved document issues

### ISSUE THREAD

**Issue by thabse** [belav/csharpier#647]
I'm having some issues when trying to format a document that has not been written to a file (an unsaved document tab in VS Code). When triggering the *Format Document (Shift + Alt + F)* command, VS Code indicates that the formatting is in progress. However, the formatting never finishes and VS Code keeps showing the busy indication indefinitely or until I switch to another document. 

After starting the formatting, I can observe:
- The document does not get formatted
- VS Code Memory usage increases by about 10 MB per second (no end in sight)
- VS Code uses about 12% CPU
- When restarting VS Code and switching to the unsaved document I tried to format, the Memory leak and CPU usage shows the same pattern again (without triggering another format, see [1] for a possible cause) 
- Closing the document does not stop the Memory leak or the CPU usage
- Disabling the CSharpier extension (and performing the reload that VS Code suggests) does not stop the Memory leak or the CPU usage
- When the CSharpier extension is not installed or disabled when starting VS Code, non of the above behavior occurs (or in other words: everything works as expected)

[1]: After some further experimentation I noticed that as soon as I switch to an unsaved document in language mode *C#* (can be an empty document), the memory leak and CPU usage occurs. So this issue is not only triggered by formatting, but also by switching to an unsaved document in language mode *C#*. However, opening a new document (no language specified) and pasting C# code or manually changing the language mode to *C#* does not trigger this behavior (but selecting any other document and switching back to this new one does).

----

CSharpier Info:
Extension Version: v1.2.1
CSharpier is globally installed with version: 0.16.0

VS Code Info:
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by belav** [comment]
Thanks for all of the details. I was able to recreate this using the basic steps you provided so I think I have all the info I need to get a fix out. I am fairly certain I tested formatting unsaved documents with the initial version of the vscode extension, but I don't have it in my test cases so must have broken it at some point.

I should have a fix for this out this weekend, possibly even tonight if I can squeeze it in.

**Comment by belav** [comment]
I have a quick fix for the problem already, it was a bad assumption inside of a loop that caused it to loop forever.
Version 1.2.2 should be available shortly and fixes the issue. I'll clean up the fix this weekend when I have more time.
Sorry for any pain and suffering this caused you!

**Comment by thabse** [comment]
Thanks for your quick reply and fix!
While the memory and CPU issue is fixed, the document still does not get formatted.

Output from a successful format of a __saved document__:
```
["INFO" - 07:44:36] Formatting started for <path-to-file/>.
["DEBUG" - 07:44:36] Got chunk of size 160
["DEBUG" - 07:44:36] Got last chunk with ETX at 159
["INFO" - 07:44:36] Formatted in 1.7976000308990479ms
["DEBUG" - 07:44:36] result is empty
```

Output when attempting to format an __unsaved document__:
```
["INFO" - 07:44:24] Formatting started for Untitled-1.
["INFO" - 07:44:24] Formatted in 0.30149996280670166ms
["DEBUG" - 07:44:24] result is empty
```

**Comment by belav** [comment]
Ah whoops! I was doing my quick test with just an empty document so didn't notice that. I will have a proper fix out for it this weekend, and I'll make sure to test properly then.

**Comment by belav** [comment]
Version 1.2.3 should be available shortly and actually formats unsaved documents now.

It will treat the unsaved document as if it were in the root of your workspace, using a local version of csharpier if there is one and the global version if there is not. In the case of a multi-root workspaces it will use the first workspace. I imagine c# projects don't often use that feature and wasn't sure how else to handle the situation.

**Comment by thabse** [comment]
Thanks, the issue seems to be resolved.
