### ISSUE TITLE
Invalid code for comments inside expressions in verbatim interpolated strings

### ISSUE THREAD

**Issue by ivan-razorenov** [belav/csharpier#679]
Reproduction: format
```
class ClassName
{
    void MethodName()
    {
        return $@"
            {
            // comment
            "hi"
            }
        ";
    }
}
```
which will produce
```
class ClassName
{
    void MethodName()
    {
        return $@"
            {
        // comment "hi"}
        ";
    }
}
```

**Comment by belav** [comment]
Not only did I not realize new lines were allowed within an expression in an interpolated verbatim string, but there were apparently no instances of this within all the public repos I test on.
I can have this fixed pretty easily, thanks for reporting it.
