### ISSUE TITLE
option for newline convention?

### ISSUE THREAD

**Issue by bwiklund** [belav/csharpier#691]
hi! love this tool, it's a big upgrade from roslyn/omnisharp imo. ❤️ 

any chance we could get an option for newlines after braces? my experience with coworkers has been typically "new lines after the {", which is also backed up by this extremely unscientific poll:

![image](https://user-images.githubusercontent.com/3586801/174456908-3fd5de50-50d8-4909-a1f4-cf9edcb8e43c.png)
https://twitter.com/daisyowl/status/1537933370167918597

i appreciate that the goal of this (and the original prettier) is to be opinionated and eliminate debate about formatting, but in this case I honestly feel that the community is pretty split. and the current unchangable default is gonna prevent us from using this tool

**Comment by belav** [comment]
From what I know, Allman style is pretty much the standard in c#.
```
while (x == y)
{
    something();
    somethingelse();
}
```
All the official Microsoft documentation uses it, all IDEs default to it, every repo I use to test csharpier uses it. 

It could be that people misunderstood what the poll was asking. When I first read the poll, my thought was "of course you want a new line after a {".

When I first tried out prettier I hated the way it formatted code. But after a week I got used to the way prettier formats things, and the old way I formatted code looked wrong. And every new person added to our team didn't bring a new way to format code. And I spent no time during code reviews thinking about or giving feedback on the way someone formatted code.

I think you should try out csharpier for a week, set it up to format on save in your IDE, and see if you still care how braces are formatted.

**Comment by bwiklund** [comment]
hm, you make a good point about my wording of that twitter poll...

you're right about all the philosophic reasons for prettier, and if I was on a larger team I'd probably just accept Allman style... but I am stubborn... maybe I'll run csharpier first to actually clean up lists and anonymous functions THEN run roslyn to get my braces style 😈

**Comment by bwiklund** [comment]
thanks for taking the time to reply btw!

also: would it be trivial for me to fork the project and change the indentation style just for my own use, or would that be a whole can of worms?

**Comment by belav** [comment]
> maybe I'll run csharpier first to actually clean up lists and anonymous functions THEN run roslyn to get my braces style

That is definitely an option. It may be harder to enforce a check for formatting, but if you just want to clean up a codebase it would definitely work. CSharpier also conforms to most style cop rules, there is a doc page calling out the rules that conflict. Or dotnet format I am pretty sure has a configuration option for braces style.

> also: would it be trivial for me to fork the project and change the indentation style just for my own use, or would that be a whole can of worms?

It may not be too bad, but I don't think I'd call it trivial. I think you would want to look for all instances of `OpenBraceToken` that are inside of the `SyntaxNodePrinters` folder. The basic idea is that a lot of them result with something like this
```
Doc.HardLine, Token.Print(node.OpenBraceToken), Doc.HardLine
```
And you'd instead want it to be
```
" ", Token.Print(node.OpenBraceToken), Doc.HardLine
```

But the change isn't necessarily as straightforward as that.

If you make all the changes you want to end up with to the test files at `Src/CSharpier.Tests/FormattingTests/TestFiles` you can make sure you aren't missing anything.

> thanks for taking the time to reply btw!

You're welcome! Getting the first request to add a printing option is kind of a milestone. At this point apparently prettier just closes them without comment.

**Comment by shocklateboy92** [comment]
Personally, I got used to the Java/JavaScript (and most languages I can think of that use curlies) way of formatting (with `{` before the line break). I think it looks much nicer and would simplify csharpier's formatting rules because it would make `{` handling the same as `(`, `[`, and `<`.

But, I think we will have a much harder time convincing the C# community to use csharpier if we made that our style. (And we definitely don't want to go the options route).

**Comment by JimmyZJX** [comment]
I basically followed instructions from @belav and got my own [fork](https://github.com/JimmyZJX/csharpier). Just in case people (or myself) want to use it in the future.

<img width="944" height="872" alt="Image" src="https://github.com/user-attachments/assets/29f7b2ae-b440-40a6-bf34-4a2f605bf30c" />

**Comment by bwiklund** [comment]
nice, just tried this out

one thing: it still puts a newline after the parens in a `new() { ... }` expression

**Comment by JimmyZJX** [comment]
@bwiklund Yes, there are still some edge cases. Could you open issues in my repo? I'll try to address them soon.

**Comment by bwiklund** [comment]
i might be misunderstanding the github ui but i don't think i'm able to file issues on your fork

**Comment by JimmyZJX** [comment]
@bwiklund My bad. Just enbled issues in my fork. (GitHub by default disables it on forks)

**Comment by 12joan** [comment]
> I basically followed instructions from [@belav](https://github.com/belav) and got my own [fork](https://github.com/JimmyZJX/csharpier). Just in case people (or myself) want to use it in the future.

@JimmyZJX Thanks for this! We've published a compiled version of your fork as [CSharpierABS](https://www.nuget.org/packages/CSharpierABS). The command is `csharpier-abs` instead of `csharpier` to avoid conflicts when multiple versions are installed.

We probably won't release updates to this version unless we encounter issues with it ourselves, but hopefully it will be useful to anyone wanting a quick fix. I'm hoping that this can be enabled as an option in the official version at some point; it seems like it would fit well with the other opinion-based options already supported in the [config file](https://csharpier.com/docs/Configuration).

**Comment by belav** [comment]
> I'm hoping that this can be enabled as an option in the official version at some point; it seems like it would fit well with the other opinion-based options already supported in the config file.

CSharpier will not be adding this as an option.
