### ISSUE TITLE
IDE plugin format on save as a per-project setting

### ISSUE THREAD

**Issue by mbcrawfo** [belav/csharpier#696]
Problem: I like csharpier and want to use it, so I install the plugin for my editor and turn the format on save setting.  Unfortunately not all of the projects I work on use it, and when I switch to one of those projects I often forget about the auto formatting until I go to commit and notice a lot of formatting changes.

I can think of a few possible solutions to this issue:

1. Replace the current (boolean on/off) IDE format on save setting with a dropdown that has options such as 'Never', 'Always', and 'When the project uses CSharpier'.  CSharpier usage in a project could be detected by checking the project's `dotnet tool list`, or looking for the presence of one of the config files.
2. Add a setting to the configuration such as `formatOnSave: boolean`.  The setting would be ignored by the tool itself and used by IDE plugins.
3. Most IDEs have a way to do project specific configuration that overrides the IDE global settings, so assuming that's expose through their plugin API it could be used to provide a project specific setting.

**Comment by belav** [comment]
I had meant for these settings to be per project, which is how they work in the rider plugin. I don't normally work in VisualStudio, but I did confirm that the setting is not per project. I am fairly certain it will be possible to turn the existing setting into a project specific setting.

**Comment by belav** [comment]
I was able to get this working per project, but supporting both global and per project settings was proving difficult. I created #705 for supporting both. Per project only seems better than global only. You can eventually get all the project settings the way you want and won't need to flip a setting back and forth depending on which project you are working in.
The changes will be released shortly.
