### ISSUE TITLE
Support global or local settings in the VS plugins

### ISSUE THREAD

**Issue by belav** [belav/csharpier#705]
Visual Studio plugins don't support a way to store options from a dialog in a way that you can define global values, and have them overridden with local values stored with the solution.

The changes in https://github.com/belav/csharpier/tree/vs-better-settings are a start of that, but there are still a number of issues not solved.

1. The dropdown for storage type determines what value will be used for a given option. If you define local settings for a solution, but then switch the dropdown to global, then the global value is used. Or in other words, the local settings will not automatically override the global settings. Which is how other IDEs work.
2. The above would be okay probably be okay, except that the storage type option is not persisted anywhere. The current code makes it not super straightforward to persist the value. Maybe the options page could use the typical storage for that setting somehow.

The changes in #702 make the options local only, which I believe is better than global only. But figuring out either 1 or 2 above would give more flexibility to the user.

**Comment by BenasB** [comment]
Some time ago, [VS introduced "Code Cleanup"](https://devblogs.microsoft.com/visualstudio/bringing-code-cleanup-on-save-to-visual-studio-2022-17-1-preview-2). There is a fixer "Format Document", but AFAIK it uses the VS in-built formatter. I wonder if there's a possibility to add these fixers with an extension, if so, having one for csharpier would be a good option to support it globally (these cleanup profiles are global)

**Comment by BenasB** [comment]
As a workaround, it is possible to get the "Format on save" globally using https://github.com/Elders/VSE-FormatDocumentOnSave and setting `Command` option to `EditorContextMenus.CodeWindow.ReformatWithCSharpier`
