### ISSUE TITLE
Unicode characters are lost during format on save

### ISSUE THREAD

**Issue by mstijak** [belav/csharpier#713]
I experience the same issue as #545 with the latest version of the CSharpier extension and VS2022.

All Unicode characters are replaced with ASCII versions or question marks during the format. For example, `Š` becomes `S`.

This is a good file for reproducing the issue:
https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/ASCIIFoldingFilter.cs

I tried to provide a failing test, but I cannot build the project on my machine.

**Comment by belav** [comment]
I haven't been able to reproduce this so far.
I tried with 
VS2022 Professional 64bit 17.3.0 and 17.2.5 (I think? I updated to latest after it worked on the 17.2.x version I had)
CSharpier 0.18.0
CSharpier Plugin 1.3.0
Windows 10 

I tried both the right click "Reformat with CSharpier" as well as format on save.

With the interactions between the plugin and csharpier, providing a test is harder. As far as I know csharpier itself has handled unicode properly for quite a while.

Could there be something else running on save? You could disable the format on save of csharpier, and see if you still lose unicode. Files that start with `// <autogenerated ` also get ignored by csharpier

**Comment by belav** [comment]
One thing I just thought of but am not able to test right now - this could have to do with the file encoding. When I tested, I copied the contents into a new file. I'll test with the actual file to see I can reproduce it that way.

**Comment by mstijak** [comment]
Everything is ok. This was my fault. I checked only the version of the VS extension, but the problem was with the old version of the tool. Thanks for providing the version info. That helped me realize the problem.
