### ISSUE TITLE
sort modifiers

### ISSUE THREAD

**Issue by glmnet** [belav/csharpier#725]
e.g. methods like 

````cs
public override async Task Method1() {...} 
async public override Task Method1() {...} 
```` 

are equivalent 

It'd be nice to have first visibility and last async, or whatever, but consistent.

This is similar to sort `using`s maybe and [that discussion](https://github.com/belav/csharpier/issues/661) might apply here too.

**Comment by danfma** [comment]
Can I add one more to this topic, the new `required` keyword of C# 11 is being put before the property access modifier.

So, for example, instead of having:

```csharp
public required string Name { get; init; }
```

we have:

```csharp
required public string Name { get; init; }
```
