### ISSUE TITLE
Visual Studio extension marking file as dirty when using comments on separate lines for passing arguments.

### ISSUE THREAD

**Issue by BenjaBobs** [belav/csharpier#743]
I'm not exactly sure what causes this, but here is a minimal repo:

```cs
public class Program
{
    public static void Main()
    {
        DoNothing(
            // comment addressing why we're passing "a"
            "a",
            // comment addressing "b"
            "b"
        );
    }

    public static void DoNothing(string a, string b) { }
}
```

When saving with auto-formating with CSharpier extension, the file is still dirty afterwards.
The effects of this is that any breakpoints placed will not be hit because visual studio thinks that the source code is different than the compiled program.

**Comment by BenjaBobs** [comment]
Might be related to https://github.com/belav/csharpier/issues/739

**Comment by BenjaBobs** [comment]
Update:
I was previously running VS version `17.4.0 preview 2.0`, but I have since upgraded to version `17.4.0 preview 4.0` and I no longer experiencing the issue.

**Comment by belav** [comment]
It sounds like maybe this was just a bug with `17.4.0 preview 2.0` then? I can't reproduce it in `17.3.5`

**Comment by BenjaBobs** [comment]
In that case I think you're right. I'll close the issue.

**Comment by BenjaBobs** [comment]
This is now confirmed to be a [Visual Studio bug](https://developercommunity.visualstudio.com/t/Visual-Studio-clears-dirty-flag-before-c/10124978), which has been [fixed in preview versions](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.4.0-pre.5.0).
