### ISSUE TITLE
VSCode extension fails to format .cs file

### ISSUE THREAD

**Issue by insraq** [belav/csharpier#749]
Formatting does not work. I checked the debug output and this is the error message

```
["WARN" - 5:05:10 PM] Exception while running 'dotnet csharpier --version' in C:\Users\<WITHHELD>\AppData\Local\CSharpier\0.20.0
"Cannot use file stream for [C:\\Users\\<WITHHELD>\\AppData\\Local\\CSharpier\\0.20.0\\.store\\csharpier\\0.20.0\\csharpier\\0.20.0\\tools\\net6.0\\any\\dotnet-csharpier.deps.json]: No such file or directory\r\nA fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\\Program Files\\dotnet\\'.\r\nFailed to run as a self-contained app.\r\n  - The application was run as a self-contained app because 'C:\\Users\\<WITHHELD>\\AppData\\Local\\CSharpier\\0.20.0\\.store\\csharpier\\0.20.0\\csharpier\\0.20.0\\tools\\net6.0\\any\\dotnet-csharpier.runtimeconfig.json' was not found.\r\n  - If this should be a framework-dependent app, add the 'C:\\Users\\<WITHHELD>\\AppData\\Local\\CSharpier\\0.20.0\\.store\\csharpier\\0.20.0\\csharpier\\0.20.0\\tools\\net6.0\\any\\dotnet-csharpier.runtimeconfig.json' file and specify the appropriate framework.\r\n"
["ERROR" - 5:05:10 PM] ,,Tool 'csharpier' is already installed.

["DEBUG" - 5:05:10 PM] returning NullCSharpierProcess because of the previous error when trying to set up a csharpier process
```

Operating System: Windows 11
dotnet --version: 6.0.202

Running `dotnet csharpier --version` in the built-in terminal works and prints `0.20.0`

**Comment by belav** [comment]
The IDE extensions use a version of csharpier installed to a custom location. This error sounds like that install is somehow corrupted. You could test it by running this
```
C:\Users\<WITHHELD>\AppData\Local\CSharpier\0.20.0\dotnet-csharpier --version`
```

Deleting that directory and restarting VSCode would get the extension to reinstall csharpier in the custom location.

In the past I've seen errors that seemed related. It could be that the custom install is sometimes interrupted and leaves the install directory in a non-working state. I think the other errors usually involved an empty directory though. It may be that I need to tweak the extensions again to get them smarter about installing csharpier or smarter about detecting conditions like this and recovering from them.

**Comment by insraq** [comment]
Thanks, deleting the folder and reinstall via `dotnet tool uninstall / install` works wonders!
