### ISSUE TITLE
Can't see CSharpier under Tools in VS2022

### ISSUE THREAD

**Issue by Xyloto91** [belav/csharpier#751]
Hi, installed extension for VS2022 Community edition and I don't see CSharpier under Tools -> Options. I installed same extension on VS2019 and there I see CSharpier under Tools -> Options.

**Comment by belav** [comment]
I'm running VS2022 pro 17.3.5 and this is where the CSharpier options show for me
![image](https://user-images.githubusercontent.com/3606529/200646773-4dcdd0d0-2870-423b-935c-47e667d04d71.png)

Is there any information in the CSharpier Output window that could indicate some kind of exception being thrown?

**Comment by Xyloto91** [comment]
Reinstalled today VS2022 and installed newer version 17.4.0, now I see CSharpier.
Before reinstall I didn't saw any exception in Output window, but when I executed "dotnet csharpier ." it would format my code but I couldn't see option "Reformat with CSharpier" when I right click in VS editor.
