### ISSUE TITLE
CSharpier not formatting file with error

### ISSUE THREAD

**Issue by JBVector** [belav/csharpier#783]
Hello.
I just installed the CSharpier for VSCode extension, and whenever I click format document, it gives me this. It doesn't appear to do anything to the file. Any help would be appreciated!

["INFO" - 6:07:59 PM] Formatting started for c:\Users\JBVector\Desktop\Trainz\Files\Assets (Game-Ready)\TrainCars\Prestwin diag 277\eWagon.cs.
["DEBUG" - 6:07:59 PM] Got chunk of size 1
["DEBUG" - 6:07:59 PM] Got last chunk with ETX at 0
["INFO" - 6:07:59 PM] File is ignored by .csharpierignore or there was an error
["INFO" - 6:07:59 PM] Formatted in 6.7542000114917755ms
["DEBUG" - 6:07:59 PM] result is empty

**Comment by BenasB** [comment]
Any chance this is related to #784 ?

**Comment by JBVector** [comment]
> If you run csharpier against that file directly, does it work?
> 
> You may need to install csharpier with `dotnet tool install -g csharpier` And then `dotnet csharpier c:\Users\JBVector\Desktop\Trainz\Files\Assets (Game-Ready)\TrainCars\Prestwin diag 277\eWagon.cs`

When I do that it says this:

C:\Users\JBVector>dotnet csharpier C:\Users\JBVector\Documents\eWagon.cs
Error C:/Users/JBVector/Documents/eWagon.cs - Failed to compile so was not formatted.
Total time:                                                                          692ms
Total files:                                                                           1

C:\Users\JBVector>

C:\Users\JBVector>

**Comment by verdverm** [comment]
I have a similar issue. A file with a compilation error does not format. I do get the following

```
$ dotnet csharpier in.cs 
Error ./in.cs - Failed to compile so was not formatted.
  (3,102): error CS1002: ; expected
Total time:                                                                          138ms
Total files:                                                                           1 
```

However, I'd like to get the error using the API, but it seems this is not possible currently.

Looking at https://github.com/belav/csharpier/blob/master/Src/CSharpier/CodeFormatter.cs it seems the public methods only return the `result.Code` field. Could we add something like `FormatWithErrors` and `FormatWithErrorsAsync` that exposes the more complex return `CodeFormatterResult`?

- https://github.com/belav/csharpier/blob/master/Src/CSharpier/CodeFormatter.cs#L16 (public, only string return)
- https://github.com/belav/csharpier/blob/master/Src/CSharpier/CodeFormatter.cs#L76 (private, returns `CodeFormatterResult`

**Comment by belav** [comment]
> When I do that it says this:
> 
> C:\Users\JBVector>dotnet csharpier C:\Users\JBVector\Documents\eWagon.cs Error C:/Users/JBVector/Documents/eWagon.cs - Failed to compile so was not formatted. Total time: 692ms Total files: 1
> 

CSharpier needs to be able to produce a syntax tree of a file in order to format it and if it is unable to compile the file it can't produce a syntax tree. Does the file compile in VSCode? If so, can you share the contents of the file?

#710 is for making it more obvious why CSharpier is not formatting a file.

**Comment by belav** [comment]
@verdverm I created #799 for exposing more info in the API.  I wanted to keep the public surface area to a minimum and just expose things as they were requested so that I was free to change the internals without affecting the API.

**Comment by JBVector** [comment]
> 
It doesn't let me upload it, so here is a link to the file:
https://drive.google.com/file/d/18uDaSd1byrJje8eJKKmQDO9WrGAktQXv/view?usp=sharing

**Comment by JBVector** [comment]
> 
here is a link to the file

**Comment by belav** [comment]
eWagon.cs is not valid c#. It appears to be some type of a script that uses mostly c# syntax, but it contains things that are not c#.
