### ISSUE TITLE
Visual Studio 2022 extension fails to load

### ISSUE THREAD

**Issue by Seledrex** [belav/csharpier#791]
When opening Visual Studio, I am greeted with an error message stating "The 'CSharpierPackage' package did not load correctly.". Inside the ActivityLog.xml, the following is found:

```
<entry>
  <record>330</record>
  <time>2023/01/14 12:20:02.568</time>
  <type>Error</type>
  <source>VisualStudio</source>
  <description>SetSite failed for package [CSharpierPackage]Source: &apos;System&apos; Description: The system cannot find the file specified&#x000D;&#x000A;</description>
  <guid>{D348BA73-11DC-46BE-8660-6D9819FC2C52}</guid>
  <hr>0x80004005 - E_FAIL</hr>
  <errorinfo></errorinfo>
</entry>
```

How can this problem be resolved? I am able to make CSharpier work via command line fine, but using it with the Visual Studio extension would be even better.

Visual Studio 17.4.4
dotnet-csharpier 0.21.0
CSharpier Extension 1.3.5

**Comment by Seledrex** [comment]
I restarted my PC and everything seems to work now. 🙃

**Comment by TransientError** [comment]
This happened to me this week. For me, it was because I had uninstalled .NET runtime. Hopefully this will help someone in the future.

**Comment by TrawenCZ** [comment]
Happened to me now, PC restart did not resolve it, but **updating Visual Studio and its Build Tools** through Visual Studio Installer made it disappear.
