### ISSUE TITLE
Make compile errors public when using CSharpier.Core

### ISSUE THREAD

**Issue by belav** [belav/csharpier#799]
This is a suggestion from #783 

> I'd like to get the error using the API, but it seems this is not possible currently. (https://github.com/hofstadter-io/hof/blob/_dev/formatters/tools/csharpier/Program.cs)

> Looking at https://github.com/belav/csharpier/blob/master/Src/CSharpier/CodeFormatter.cs it seems the public methods only return the result.Code field. Could we add something like FormatWithErrors and FormatWithErrorsAsync that exposes the more complex return CodeFormatterResult?

**Comment by verdverm** [comment]
Can confirm this is working for my use case, thanks @belav 

https://github.com/hofstadter-io/hof/blob/_dev/formatters/test/cs_fail.txt
