### ISSUE TITLE
Rider formatting has conflict with csharpier

### ISSUE THREAD

**Issue by mehdihadeli** [belav/csharpier#801]
Hi,
I format code with `csharpier rider plugin` on save, but when I use `ctr+k+d` for applying format, it applies rider styles and they have conflict

**Comment by belav** [comment]
I'm not clear on what the ask is here. Rider formatting is configurable and may not even have options to become perfectly aligned with csharpier. If there are specific conflicts that would improve the formatting csharpier does, I'm open to suggestions.

**Comment by mehdihadeli** [comment]
@belav  So when we use `csharpier` we should not use rider formatting, correct?

**Comment by mehdihadeli** [comment]
Yes, Thanks
