### ISSUE TITLE
Some questions about version/vsix/...

### ISSUE THREAD

**Issue by Cyber1000** [belav/csharpier#805]
Hi,

thanks for this plugin, just a few questions:
- VS-Marketplace lists this as version 1.3.6 whereas github lists release 0.22.1. Is this a mistake?
- any plans to push this extension also to https://open-vsx.org? (an alternative registry if you use vscodium instead of vscode like me)
- if not at least a vsix would be nice added to every release (but haven't seen a github-workflow here, that creates releases)

Thanks

**Comment by belav** [comment]
> VS-Marketplace lists this as version 1.3.6 whereas github lists release 0.22.1. Is this a mistake?

They are versioned independently. The plugins all use the main csharpier dotnet tool to format, and support older versions of csharpier.

> any plans to push this extension also to https://open-vsx.org/? (an alternative registry if you use vscodium instead of vscode like me)

I wasn't aware of open-vsx.org until now, but I don't see any reason not to publish there. I created #806 to keep track of it.

> if not at least a vsix would be nice added to every release (but haven't seen a github-workflow here, that creates releases)

I keep meaning to automate it, but haven't made the time yet. I threw up the 1.3.6 release just now - https://github.com/belav/csharpier/releases/tag/vscode-1.3.6

**Comment by Cyber1000** [comment]
Thanks for the information! 

open-vsx came up, because microsoft marketplace and access to the marketplace is closed source: https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code
It's often used in vscodium, gitpod, ... setups where microsoft marketplace is missing.

Thanks for the package I downloaded it from microsoft marketplace,there is some link schema, that allows to download vsix directly: [https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${publisher}/vsextensions/${extension}/${version}/vspackage](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/$%7Bpublisher%7D/vsextensions/$%7Bextension%7D/$%7Bversion%7D/vspackage)

I'll close this , all answered so far!
