### ISSUE TITLE
Publish to https://open-vsx.org/

### ISSUE THREAD

**Issue by belav** [belav/csharpier#806]
Looks like it requires some signup, creating an access token, etc.

Automat this + the current release process.

**Comment by Cyber1000** [comment]
Official HowTo for this: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
At the end there is a link to the github action publish-vscode-extension which can do this: https://github.com/HaaLeo/publish-vscode-extension#readme 
❗  this github action can not only publish to openvsx but also to https://marketplace.visualstudio.com

**Comment by belav** [comment]
This is now being published to https://open-vsx.org/extension/csharpier/csharpier-vscode
