### ISSUE TITLE
tabWidth setting not applied

### ISSUE THREAD

**Issue by seraku24** [belav/csharpier#807]
I have the following `.csharpier.json` file:

```json
{
  "printWidth": 96,
  "useTabs": false,
  "tabWidth": 2
}
```

While the setting `printWidth` is working, the formatted file always prefers the default four spaces, ignoring `tabWidth`.

Item|Version
:---|---:
Visual Studio Code|1.74.3
CSharpier extension|1.3.6

**Comment by belav** [comment]
The proper file name is `.csharpierrc.json` but since `printWidth` is working I assume that was just a typo.

What version of csharpier is being used? It is versioned independently of the extension. Support for `useTabs` and `tabWidth` was added around 0.17.0 if I remember correctly.

**Comment by seraku24** [comment]
The configuration filename was just typed incorrectly in the description; sorry about that. However, the issue indeed was an old version of the tool itself, which was still stuck on 0.16.0.

For reference, I updated only to 0.17.0 and can confirm that the `tabWidth` setting works. Of course, I have gone ahead and installed 0.22.1 which is the latest listed on the nuget gallery.

**Comment by belav** [comment]
I'm going to update the doc to reflect when options were added, this has come up before and that will hopefully help avoid any confusion.
