### ISSUE TITLE
Request: Allow comment-description suffix to csharpier-ignore comments

### ISSUE THREAD

**Issue by Strepto** [belav/csharpier#835]
I would like to be able to specify a "WHY" comment after I add `//csharpier-ignore`

Example (which is not possible today)
```
// csharpier-ignore-start -- Keep Matrix formatting
float m11 = m.M11, m12 = m.M12, m13 = m.M13;
float m21 = m.M21, m22 = m.M22, m23 = m.M23;
float m31 = m.M31, m32 = m.M32, m33 = m.M33;
// csharpier-ignore-end
```

or 

```
// csharpier-ignore -- Class copied as-is from other project, want to keep formatting
internal class Euler {
```

CSharpier v0.21 does not find comments which start with `// csharpier-ignore` but have a different ending. 

This is a suggestion seen in eslint, and I find it useful to keep the "why-comment" inline.

Example from eslint docs on this feature: <https://eslint.org/docs/latest/use/configure/rules#configuration-comment-descriptions>
`/* eslint eqeqeq: "off", curly: "error" -- Here's a description about why this configuration is necessary. */`

Suggested allowed (regexish) format ([tests](https://regexr.com/78ogq)):

`\/\/ csharpier-ignore($| --)`

This is NOT supported by `prettier` though, so feel free to close this if you feel it is out of scope.

**Comment by belav** [comment]
I'm not sure why prettier doesn't support this, it seems like a good idea to me. If someone was using `// csharpier-ignore` at work I'd like to understand why they were and this is cleaner than adding another comment above or below it.
