### ISSUE TITLE
support for razor pages? .cshtml

### ISSUE THREAD

**Issue by RaoufAlaadin** [belav/csharpier#838]
does Csharpier support .cshtml files? 
Because when I tried to open a razor project, 
It gave me an Error stating " failure to load Csharpier"

**Comment by belav** [comment]
There is an open issue (one of the very oldest) for supporting razor files
but no support as of now.

The plugins for IDEs only try to format c# files, where are you seeing the
error about failing to load CSharpier? Does formatting work on regular c#
files?

**Comment by RaoufAlaadin** [comment]
Yes, formatting works on regular .cs files, 
it only started acting weird when I tried to open an asp.net mcv (.NET framework) project.
And it gave the following error. 

https://ibb.co/7t4m60Y

**Comment by belav** [comment]
Maybe the razor project is just a coincidence. Does the file that the error links to have any useful information? I believe this is a problem with loading the extension.

A couple of things to try to see if you can get it working (although I'm still curious what's in the file just in case this is something I can fix)

- see if the output window for csharpier has any information - although if it is failing to load I don't know that anything would end up logged there
  - turning on the option for log debug messages under - options - csharpier may give more information.
- delete the folder at `[projectRoot]/.vs/CSharpier` if it exists, restart visual studio
- uninstall the extension, restart visual studio, install it again

**Comment by RaoufAlaadin** [comment]
It happens even when creating a new clean project, it’s not dependent on the content written.  
gonna try what you suggested 👍

**Comment by belav** [comment]
There was a problem with the VS2019 version of the extension that is fixed as of 1.4.0. Based on the popup you were seeing I think you are on 2022 though.
