### ISSUE TITLE
VSCode extension can't find the global CSharpier

### ISSUE THREAD

**Issue by yukw777** [belav/csharpier#859]
I just spent a couple of hours trying to debug this, but haven't been able to pinpoint the issue. My PATH for both zsh and bash are set correctly and I can run `dotnet csahrpier --version` just fine, but for some reason the VSCode extension keeps complaining that it can't find it and I need to install it. If I tell it to install csharpier, it says it did (which is odd since csharpier is already installed), but continues to complain. I feel like there's something weird going on with the PATH variable. I am using the remote ssh extension, so this is happening on the remote machine.

Debug log:

```
["DEBUG" - 1:22:02 PM] Unable to find dotnet-tools.json, falling back to running dotnet csharpier --version
["DEBUG" - 1:22:03 PM] dotnet csharpier --version failed with Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-csharpier does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by belav** [comment]
When you are running the command are you running it locally or on the remote machine?
It could be that the extension is trying to run the dotnet commands in the incorrect location. From my understanding Remote SSH dev (I just read up on it now) I believe the desired behavior would be to have the csharpier extension running as a workspace extension. The extension doesn't specifically set `extensionKind` in the manifest, and it isn't clear what the default value is.

The extension does work with devcontainers but only when csharpier is installed as a local tool. A possible workaround for remote ssh dev would be to run `dotnet tool install csharpier` on the remote host and then restart vscode.
