### ISSUE TITLE
VS 2022 freeze on files with compilation errors

### ISSUE THREAD

**Issue by vabic** [belav/csharpier#866]
Hello.
1. I installed csharpier with dotnet tool for my solution. I installed VS extension (v 1.4.0)and activate CSharpier - Solution format on save.
 2. For clean up using's and format Razor files, I use [FormatAndSave](https://marketplace.visualstudio.com/items?itemName=WinstonFeng.VSFormatOnSave2022). Both work great together.
 3. If a have a file with compilation errors, VS freeze for always. 
 4. Kill the process dotnet-csharpier.exe unfreeze VS (the workaround I use for, but not ideal).
 5. Disable FormatAndSave extension don't freeze VS but this is not an option :(
 
Any suggestion?

 dotnet-tools.json: 
`{
  "version": 1,
  "isRoot": true,
  "tools": {
    "csharpier": {
      "version": "0.23.0",
      "commands": [
        "dotnet-csharpier"
      ]
    }
  }
}`

**Comment by belav** [comment]
I haven't been able to reproduce this. I did verify that FormatOnSave was working. But only had the basic options configured. I don't think the options from FormatOnSave would affect it, but could you share how you have it configured?

Could you turn on "Log Debug Messages" (may need to restart VS afterwards), and see what the output window for csharpier shows when VS freezes?

Does this happen with every file? My test case was a very simple c# class.

**Comment by vabic** [comment]
In my case, VS freeze with a very simple project https://github.com/vabic/csharpierFreezeSample.git. 
Add somewhere in the code some random characters to have errors. (ex: line 51    `Console.Clear(); $$###$##`)
After some Ctrl+s (up to 5 time) VS freeze.
 
NB: Output windows for csharpier do nothing because VS is totally freeze.

**Comment by Pentadome** [comment]
It seems to be very random about when it freezes on compile error and when not. Unfortunately whole VS freezes and only unfreezes when I kill `dotnet-csharpier.exe`. Maybe adding a command timeout could be a good (enough) solution?

**Comment by belav** [comment]
@vabic I was finally able to reproduce it using your repository. I couldn't determine exactly what was causing it to hang, but the suggestion from @Pentadome worked with a little bit of tweaking.

I'll have a new version out shortly
