### ISSUE TITLE
Nested loops without brackets may be not indented

### ISSUE THREAD

**Issue by Rudomitori** [belav/csharpier#867]
```C#
// With CSharpier 23
foreach(var subsequnce in sequance)
    foreach(var item in subsequance)
        item.DoSomething();

// How it might look like 
// and how Rider 2023 formats it
foreach(var subsequnce in sequance)
foreach(var item in subsequance)
    item.DoSomething();
```

```C#
// With CSharpier 23
foreach(var subsequnce in sequance)
    foreach(var item in subsequance) {
        item.DoSomething();
        item.DoSomething();
    }

// How it might look like 
// and how Rider 2023 formats it
foreach(var subsequnce in sequance)
foreach(var item in subsequance) {
    item.DoSomething();
    item.DoSomething();
}
```

The same for `await foreach`, `while` and `for` loops;

The second variant removes one indentation level
and look pretty for me.

Also, CSharpier already use the second variant for `using` statements
and if the same will be done for loops it will be more consistent.

```C#
using (var fileStream1 = File.OpenRead("SomeFile"))
using (var fileStream2 = File.OpenRead("OtherFile"))
{
    Console.WriteLine("Hello");
    Console.WriteLine("World");
}
```

**Comment by belav** [comment]
I hadn't seen this before, but it makes sense to me and does keep things consistent with `using`. I'll want to do a bit of digging into how often each variation shows up before I commit to doing it. But Rider formatting things that way by default makes me think it's more common than I initially though.

**Comment by loraderon** [comment]
I don't think that this is a good idea.

The case with using statments is the outlier and will probably be used less and less in the future because of the realtive new `using var = ..`

**Comment by shocklateboy92** [comment]
Thinking about this, it makes sense to go with this route. 

It's pretty easy to opt out by putting braces around the foreach. Since most IDEs auto add the braces by default, the two loops must be super tightly related for the user to explicitly choose to remove the braces.
