### ISSUE TITLE
Ability to disable log spam

### ISSUE THREAD

**Issue by samtrion** [belav/csharpier#875]
We are currently working on a solution with several dozen projects, where our logs are bloated with the following repetitive lines during the build process.
```pwsh
Total time:                                                                         4413ms
Total files:                                                                         145  
Files that were not formatted:                                                         0  
Total time:                                                                          507ms
Total files:                                                                           0  
Files that were not formatted:                                                         0  
```
Can these be disabled?

**Comment by belav** [comment]
There isn't currently a way to adjust the logging level but I can look at adding a way to disable/configure the level of logging.

One option for now would be to switch to running csharpier using the CLI outside of the build process. That would also cut down on the time it takes CSharpier to run, there is some initial overhead starting up the process, running it against the full solution you only get that overhead once.
