### ISSUE TITLE
csharpier-ignore comments force CRLF line endings

### ISSUE THREAD

**Issue by pingzing** [belav/csharpier#884]
I'm running into an interesting issue with line endings! I have a project configured to use `LF` line-endings, both at the .editorconfig level, and in CSharpier's `csharpierrc` config file. That works fine.

However! I have a block of code that I have `// csharpier-ignore`d. When CSharpier hits that line, it _replaces_ the `LF`s with `CRLF`s.

I'm running on Windows, and this is CSharpier v0.24.1.

Example:

No `//csharpier-ignore`:
![image](https://user-images.githubusercontent.com/5133649/235092874-f42e661e-3ad0-4864-8619-dc51f5d627ee.png)

After adding `// csharpier-ignore` and running `dotnet csharpier .`:
![image](https://user-images.githubusercontent.com/5133649/235093054-658b3aca-c9ff-4f98-bff1-667a745f7bc0.png)

What makes things even _more_ fun is that once this hits CI, it fails the `--check` check that we do, because I have git's `core.autocrlf` set to `true`, which forces all `CRLF`s to `LF`s upon pushing it up to the remote. When CSharpier's `--check` command runs in CI, it detects that it would change these `LF`s to `CRLF`s, and fails the build.

I'm not sure what my expected fix is here. Maybe make the newline-inserting that CSharpier (seems to?) do here respect `endOfLine`?

**Comment by belav** [comment]
This is a very odd issue but I have a hunch what may be going on. It could be that when csharpier asks Roslyn for the source of an ignored node, Roslyn is using CRLF.

CSharpier does have code to replace mismatched line endings in ignored code with what is configured, but I believe that only happens with statements in ranged ignores.

I'm out of town right now so can't verify the theory, but I can look at a fix when I'm back next week.

**Comment by belav** [comment]
I haven't been able to reproduce this. I tried on the file system as well as in a test, with a bunch of combinations of line endings in the file + line ending options.
https://github.com/belav/csharpier/blob/74924377e93fbc3ba76d4e9e4e58e98211c22c64/Src/CSharpier.Tests/FormattingTests/LineEndingEdgeCase.cs

CSharpier doesn't expose the line endings as an option in the `.cshapierrc`, it did originally but currently it defaults to `auto`, which formats each file based on the first line ending that it encounters in a given file. But that doesn't explain why adding `// csharpier-ignore` would cause mismatched line endings.

Could you supply the full file? Or a trimmed down version that reproduces the problem.

**Comment by pingzing** [comment]
Sure! Here's a repository that exhibits the issue: https://github.com/pingzing/CSharpierRepro

In order to reproduce it, do the following:
- Clone the repo
- Change the line endings in `Program.cs` to `LF`, by running `dotnet format`, or using the VS line ending fixer, or really, however
- Run `dotnet format .`

But here's the _really interesting_ part: If I replace the contents of `.csharpierrc.json` with an empty JSON object (i.e. just `{ }`), or just delete it altogether, _I can't reproduce the problem!_ It seems like the presence of the config file seems to change the behavior here.

**Comment by belav** [comment]
It took a bit to track down, but this had to do with the combination of preprocessor symbols + csharpier-ignore not properly replacing line endings in the ignored section of code. And of course was a one line fix once I found it. And I believe it only shows up if the file in question does not use the system's default line endings (file with LF on windows which defaults to CRLF).
I'll push out a fix for this shortly!

**Comment by pingzing** [comment]
Fantastic work! Thanks a bunch!
