### ISSUE TITLE
Unnecessary spacing in CLI output

### ISSUE THREAD

**Issue by ben-wallis** [belav/csharpier#885]
After spending 30 minutes trying to figure out why csharpier was formatting a different number of files in our CI pipeline than locally, I finally noticed that my browser window was the exact width that resulted in chopping the Total time and Total files output numbers in half:

![image](https://user-images.githubusercontent.com/11904214/235649462-eaeb78f1-4be3-4698-86a9-78eeb6669e67.png)

It may be worth considering removing the spacing to prevent this kind of misreading of the output.

**Comment by belav** [comment]
I've been considering simplifying the output for check and getting rid of the stats, I'm not sure that they add value. Prettier only provides a simple "everything is good" or "here are the files that aren't formatted" output. Maybe adding an option to show more details about the number of files, etc. If I do keep around the details I'll clean up the spacing to avoid this problem.

**Comment by belav** [comment]
Related #875

**Comment by belav** [comment]
I'm going to rework the logging and add a logging level with #875. As part of that the format is going to change which will remove this problem.
