### ISSUE TITLE
CSharpier.MsBuild returns exit code 1 when ManagePackageVersionsCentrally is set to true

### ISSUE THREAD

**Issue by adc-cjewett** [belav/csharpier#898]
When using a repository that has ManagePackageVersionsCentrally set to true we're finding that CSharpier.MsBuild returns exit code 1.
![image](https://github.com/belav/csharpier/assets/118358736/0fe986bc-46e0-40b9-98d6-fb04882b9878)
There are 3 failures because it is a multi-target library.
Reproducible example is in this repository: https://github.com/adc-cjewett/CSharpierTest

**Comment by belav** [comment]
Thanks for the reproducible example! How frustrating is this issue for you? I should be able to get a release out in the next few days if it's a blocker for you, I have the fix mostly ready to go.

**Comment by adc-cjewett** [comment]
@belav Thanks for tackling this so quickly! We aren't in a rush and I wouldn't try to impose any timeline on you. If you need any assistance testing this we'll keep an eye on the fix and try it out.
