### ISSUE TITLE
CSharpier.MSBuild runs once for each framework, can it be more efficient.

### ISSUE THREAD

**Issue by belav** [belav/csharpier#900]
When building the project at https://github.com/belav/CSharpierTest
The output contains CSharpier formatting files 3 times, once for each target framework.

Can CSharpier.MSBuild be smart enough to only format files for one of the target frameworks?

**Comment by adc-cjewett** [comment]
We had a similar issue and used this solution. Not sure if it's 100% applicable since we use a different BeforeTarget but figured I'd at least share the info. 

```
  <!-- If the project is not multi-target then run it once for the project. -->
  <Target Name="SingleTargetPathFilterUpdate"
        BeforeTargets="PreBuildEvent"
        Condition="'$(Configuration)' == 'Debug' 
            and '$(TargetFramework)' != ''">
    <PathFilterUpdateTask ProjectFilePath="$(MSBuildProjectDirectory)\$(MSBuildProjectFile)" />
  </Target>
  
  <!-- If the project is multi-target then only run once per project. -->
  <Target Name="MultiTargetPathFilterUpdate" 
          BeforeTargets="DispatchToInnerBuilds" 
          Condition="'$(Configuration)' == 'Debug' 
            and '$(TargetFrameworks)' != ''">
    <PathFilterUpdateTask ProjectFilePath="$(MSBuildProjectDirectory)\$(MSBuildProjectFile)" />
  </Target>
```

**Comment by belav** [comment]
Thanks @adc-cjewett, that helped me get to where I needed to go. It didn't quite work inside of a nuget package, but I was able to track down a workaround.
