### ISSUE TITLE
All configuration options

### ISSUE THREAD

**Issue by thedusansky** [belav/csharpier#906]
Hi team! 

Can you please confirm if those are all available options that we can use in the .csharpier config file:
(printWidth, useTabs, tabWidth, preprocessorSymbolSets)? 

Also, would version 0.24.2 work fine against the .NET 3.1 project?

Many thanks! 

Dusan

**Comment by belav** [comment]
That is correct, those are the only options available.

It hasn't been tested, but I don't see a reason why CSharpier wouldn't work on a .NET 3.1 project. You would need to have net6 or net7 installed, but as long as it can parse the files in a project, it can format them.
