### ISSUE TITLE
.net 4.7.2 not possible anymore ?

### ISSUE THREAD

**Issue by Gauthiiier** [belav/csharpier#908]
Hi,

I am trying to install the nuget package on my .net 4.7.2 project ( can't change, it's what my company uses and we're technically not able to create them in another version ) as I am trying to format a piece of code to output it on a view page.

I get the message that since neither .net 6 or 7 are installed, I can't use the package, whichever version I try. I saw somewhere in some docs that it's possible to use it with older versions of .net, but can't find that anymore.

Any tips or it just won't be possible at all ?

Thanks,
Gauthier

**Comment by belav** [comment]
Which nuget package are you trying to install? CSharpier.Core targets netstandard2.0 which I believe would work just fine with 4.7.2.

I think I was having issues with CSharpier.MSBuild when having it target netstandard. And it would require net6 or net7 installed. But it is just a msbuild command that runs the cli though against the files in a project, so I don't see why it wouldn't work in a 4.7.2 project. You may have to add the reference yourself instead of through the UI and possibly ignore a warning to get the build happy.

**Comment by Gauthiiier** [comment]
Hi, I was trying with the basic CSharpier from the manage nuget packages page in VS, I did try right now with the .Core one, but he same problem persists, still giving me this error message :
`Attempting to gather dependency information for package 'CSharpier.Core.0.24.2' with respect to project 'TIE5_WSTESTEUR', targeting '.NETFramework,Version=v4.7.2'
Attempting to resolve dependencies for package 'CSharpier.Core.0.24.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'CSharpier.Core.0.24.2'
Resolved actions to install package 'CSharpier.Core.0.24.2'
Install failed. Rolling back...
Package 'CSharpier.Core.0.24.2' does not exist in project 'TIE5_WSTESTEUR'
Package 'CSharpier.Core.0.24.2' does not exist in folder 'C:\PRIV\Projects\TIE5_DEV\TIE5_WSTESTEUR\packages'
Could not install package 'CSharpier.Core 0.24.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by belav** [comment]
If you are just trying to install csharpier, it normally isn't done through managing nuget references.

From the root of your repo if you run this, that will install csharpier and make it available via the `dotnet csharpier` command

```bash
# if you don't yet have a .config/dotnet-tools.json file
dotnet new tool-manifest

dotnet tool install csharpier
```

As for nuget packages, if you do it manually it involves editing the csproj to include the PackageReference yourself. You may have to tell VS to restore packages after doing this, I forget if it detects the change and does it for you automatically.
```xml
  <ItemGroup>
    <PackageReference Include="CSharpier.Core" Version="0.24.2" />
  </ItemGroup>
```
