### ISSUE TITLE
Strong Name Assemblies

### ISSUE THREAD

**Issue by TwentyFourMinutes** [belav/csharpier#911]
I am trying to use the `Csharpier.Core` package in a signed project. However I do get runtime exception for `Csharpier.Core` as it is not signed:
> Referenced assembly 'CSharpier, Version=0.24.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

In essence to fix this [create a `.snk` file](https://learn.microsoft.com/en-us/dotnet/standard/assembly/create-public-private-key-pair) and enter the following command in a `Developer Command Prompt for VS`:
> sn -k csharpier.snk 

Move the file to the same location as the `Directory.Build.props` and add the following inside the `Directory.Build.props` file:
```xml
<AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)/csharpier.snk</AssemblyOriginatorKeyFile>
<SignAssembly>true</SignAssembly>
```

Would be an easy fix and doesn't hurt anyone :)

**Comment by belav** [comment]
I have this basically done but ran into https://www.nuget.org/packages/Ignore not being signed. It is a small library under MIT so I'll pull in the couple of files that I need to finish this off.

**Comment by TwentyFourMinutes** [comment]
Oh, I see. If you want to offload any work, feel free to tell me. Thanks for looking into it though!
