### ISSUE TITLE
Badly formatted json configuration file hangs the IDE

### ISSUE THREAD

**Issue by BlueInt32** [belav/csharpier#912]
**Steps to reproduce**
- Install Csharpier extension in Visual Studio (Community) or Jetbrains Rider on Windows 10
- create the following configuration in the expected json file (both `.csharpierrc` or `.csharpierrc.json` will reproduce) but with a wrong format, i.e. notice the double quotes missing for properties:
```json
{
    printWidth: 120,
    useTabs: false,
    tabWidth: 4
}
```
- Set up csharpier to run on save
- Save any file (triggers the formatting)

**Expected**
The formatting does not work, something tells us that the configuration file is badly formatted.

**Actual**
The IDE (either VS or Rider) completely hangs, nothing can be done except: 
- fixing the file (which un-hangs the IDE immediately)
- killing the IDE in the task manager

**Comment by belav** [comment]
I believe I fixed this problem in #1191, when the cli was throwing an exception the plugins would hang because the cli didn't send back a response indicating it was done trying to format.
