### ISSUE TITLE
Skip CSharpier with dotnet cli property

### ISSUE THREAD

**Issue by OneCyrus** [belav/csharpier#914]
I was trying to skip CSharpier in a project where we use the msbuild nuget package. Is there a property which skips CSharpier completely? As far as I can tell the CSharpier_Check property only switches between writing format to disk or validating the format.

Something like this would be great:
`dotnet publish -c release -o /app --no-restore /p:CSharpier_Skip=true`

**Comment by belav** [comment]
Thanks for the suggestion! I went with bypass instead of skip because it sounded better when I was documenting how to make use of it.

**Comment by OneCyrus** [comment]
awesome. thank you!
