### ISSUE TITLE
This makes no sense whatsoever

### ISSUE THREAD

**Issue by aradalvand** [belav/csharpier#938]
CSharpier turns this:
```cs
var image = await db.Images
    .Where(i => i.Id == imageId)
    .Select(i => new
    {
        i.Type,
        i.VideoId,
        i.OriginalFileName,
        i.CreatedAt,
        i.Metadata,
    })
    .SingleOrDefaultAsync();
```
Into this:
```cs
var image = await db.Images
    .Where(i => i.Id == imageId)
    .Select(
        i =>
            new
            {
                i.Type,
                i.VideoId,
                i.OriginalFileName,
                i.CreatedAt,
                i.Metadata,
            }
    )
    .SingleOrDefaultAsync();
```

How any sane human being can look at this and go "yep, that's an improvement" is beyond me.
This formatting is not at all normal/common in C# (or in any freaking language, for that matter), adds not one, but two completely unnecessary levels of indentation, and three more unnecessary line breaks, and is undeniably ugly and disgusting.

Prettier doesn't do this either, this sort of formatting _might_ only make sense when multiple arguments are being passed to the method in question; it is absolutely nonsensical in cases like the one showcased above. Please reconsider.

**Comment by belav** [comment]
There are issues already open related to improving this formatting. Feel free to contribute by working on one and consider being a bit more respectful with your requests in the future.

**Comment by aradalvand** [comment]
@belav Sorry about the tone, I got really frustrated because I was almost falling in love with CSharpier and thought it was virtually perfect until I stumbled into this, which just doesn't make any sense.

**Comment by aradalvand** [comment]
> No worries, I've also had a rough day and know how that goes.

<3

> The current version was "good enough" when first working on lambdas and I haven't had a chance to get back to it yet. There are a ton of things I'd love to improve but I haven't had as much time to work on things as I used to. 

Perfectly understandable.

> I also find the more you see formatting that is consistent, even if ugly you start to get used to it and stop noticing the ugly.

True, but as you said, we can get used to anything as long as it's consistent, but that doesn't mean it's not ugly and really worth improving. I would argue CSharpier definitely needs improvement in this regard, even if one can get used to its current behavior.

Also, just noticed #672 describes more or less the same issue, so feel free to close this issue as a duplicate if you think that makes sense.

**Comment by belav** [comment]
> True, but as you said, we can get used to anything as long as it's consistent, but that doesn't mean it's not ugly and therefore worth improving. I would argue CSharpier definitely needs improvement in this regard, even if it's possible to get used to its current behavior here, it's still very unideal.

Yeah I agree, I think I was just trying to say "I kinda forget that some of this is ugly because I get used to it", and then other issues pop up and compete for attention. I'm gonna add #672 to the next milestone and hopefully get to it sooner rather than later. This or the way method calls break when they chain in some instances are probably the biggest areas for improvement right now.

**Comment by aradalvand** [comment]
> I think I was just trying to say "I kinda forget that some of this is ugly because I get used to it", and then other issues pop up and compete for attention.

Ah okay, got it!

> I'm gonna add https://github.com/belav/csharpier/issues/672 to the next milestone and hopefully get to it sooner rather than later. This or the way method calls break when they chain in some instances are probably the biggest areas for improvement right now.

Great! Thank you so much.
