### ISSUE TITLE
Not working on Visual Studio 2022

### ISSUE THREAD

**Issue by NahuFed** [belav/csharpier#961]
It fails to load the extension after a successfull installation

**Comment by belav** [comment]
Can you provide more details?
Is VS displaying an error?
Is the output window for CSharpier displaying anything?

**Comment by orlandofua-msd** [comment]
> It fails to load the extension after a successfull installation

Had this happen to me, but after updating vs2022, it worked. Doing it through the commandline with `dotnet csharpier <filehere>` worked regardless

**Comment by yukw777** [comment]
Updating VS2022 worked for me too. The error message from VS' ActivityLog.xml was something like `visual studio could not load file or assembly`.
