### ISSUE TITLE
Update VSCode doc

### ISSUE THREAD

**Issue by belav** [belav/csharpier#963]
The doc for vscode doesn't mention setting it as the formatter or the default formatter. It should include examples of that for people.
`"editor.defaultFormatter": "csharpier.csharpier-vscode"` is probably what is needed, but double check.

**Comment by HrvojeJuric** [comment]
been using this for quite a while and works good

```jsonc
{
  // ...
  
  "[csharp]": {
    "editor.defaultFormatter": "csharpier.csharpier-vscode"
  }
  
  // ...
}
```

**Comment by marcospgp** [comment]
I use this:

```
  "[csharp]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "csharpier.csharpier-vscode"
  }
```
