### ISSUE TITLE
Replaces the whole file with time status.

### ISSUE THREAD

**Issue by FormalSnake** [belav/csharpier#972]
I am using nvim format-on-save, and using this line I got it to execute the dotnet csharpier command: 	
```lua
cs = formatters.shell({ cmd = { "dotnet-csharpier", "." } }),
```
and it replaces the whole file with:
Formatted 5 files in 98ms.

**Comment by FormalSnake** [comment]
I am not sure if this is a plugin issue or a csharpier problem

**Comment by belav** [comment]
I'm not familiar with nvim format-on-save, but the command `dotnet-csharpier .` will format files in place in the location it is run from. 

If you run `dotnet-csharpier [pathToFile] --write-stdout` it would read the saved file and write the formatted results back to std out, which may work.

It is also possible to pipe input to `dotnet-csharpier --write-stdout`, which will also write the formatted results of the piped file back to std out.

You may also want to look into https://github.com/sbdchd/neoformat which has support for csharpier. The fact that it supports csharpier is the extent of my knowledge though, I don't know how it compares to nvim format-on-save.

**Comment by FormalSnake** [comment]
So, after testing the command it does not seem to output the file, even in the normal console.
<img width="859" alt="Screenshot 2023-10-06 at 22 21 42" src="https://github.com/belav/csharpier/assets/90651091/750793fb-7597-4d1a-9867-a188e222ae75">

**Comment by FormalSnake** [comment]
it only outputs when I make a change to the file

**Comment by FormalSnake** [comment]
but then the file just becomes empty when I save with no change

**Comment by belav** [comment]
Ah, it seems that there is a bug related to the caching that is done to speed up formatting when combined with `--write-stdout`. I created #973 to address that.

For now if you run with `--write-stdout --no-cache` then the file will be returned. However if there is a compilation error, then an error is written on stderror and nothing is written on stdout. I believe it also returns an exitcode of 1.

![image](https://github.com/belav/csharpier/assets/3606529/70584571-1126-4158-84e2-8ccb2fed69fb)

**Comment by FormalSnake** [comment]
Yep, that did work. But can there be an argument to not output errors and just the file without formatting?
`cs = formatters.shell({ cmd = { "dotnet-csharpier", "%", "--write-stdout", "--no-cache" } }),`

**Comment by belav** [comment]
There isn't a way to get back the file, but `--loglevel none` would prevent the error from returning. Which probably gets you back to ending up with an empty file.

Maybe your best bet for now is to wire up some basic logic that checks the exit code of csharpier, either returning the output of csharpier, or the contents of the file. Put that into a powershell or bash script, and then call that script from your formatter.

**Comment by FormalSnake** [comment]
I will try that out, I should probably open an issue in the neovim plugin aswel.
