### ISSUE TITLE
Format raw string literals indentation

### ISSUE THREAD

**Issue by jods4** [belav/csharpier#975]
CSharpier (as of 0.25.0) does not modify indentation of string literals.
The following code is left as-is:
```csharp
public class ClassName 
{
    public string M()
    {
        return """
                            This is a string that 
                            spans multiple lines
                            thanks to the new raw string feature.
                            """;
    }
}
```

I think it would be desirable to standardize the indentation of raw string literals to 1 indent more than the previous line.
I would expect the following result, which represents exactly the same string as before:
```csharp
public class ClassName 
{
    public string M()
    {
        return """
            This is a string that 
            spans multiple lines
            thanks to the new raw string feature.
            """;
    }
}
```

**Comment by belav** [comment]
This won't be super straightforward like I was hoping, but there is code somewhere else that does something similar if I can track it down.

I'm thinking that if someone already has the raw string literal dedented completely, that it should stay where it is. Something like this
```c#
public class ClassName 
{
    public string M()
    {
        return """
This is a string that 
spans multiple lines
and is really wide so someone dedented it completely
""";

        return """
            Also keep in mind
                not to dedent this line
                    and this as well
            so really just trimming the same amount off each line, which maybe is in multiline comments
            """;
    }
}

**Comment by belav** [comment]
Scanning through all the string literals in https://github.com/belav/csharpier-repos/pull/91/files there is a mix of "dedent completely" and "indent about one more than the previous line". Possibly more of the later.

**Comment by jods4** [comment]
One objective argument FOR reformatting is that CSharpier might change indentation of surrounding lines.

I personally would make no exception as the indented string just looks better and some editors don't handle code folding properly with those dedented strings.

But if you want to make an exception when the raw string indentation is exactly zero, I guess that's reasonable too.

(This is a slightly tricky feature indeed, as the spec. of raw strings is not trivial. You have to ignore empty lines, keep extra indentation on further lines and consider some literals might be invalid: less indented later lines, text on first or last line...)

**Comment by belav** [comment]
After seeing this [case](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/raw-string-literal#example-3---end-delimiter-before-start-delimiter) in the spec, I think we definitely want to have an exception for the end delimiter having zero indentation. If someone wants the resulting string to have a specific indentation, they can easily do it like this. Then they can copy/paste the raw string literal and it has the exact indentation they expect.
```c#
var xml = """
          <element attr="content">
            <body>
            </body>
          </element>
""";
```

If that was reformatted and indented like this, they would lose that ability.

```c#
var xml = """
              <element attr="content">
                <body>
                </body>
              </element>
    """;

I did get it close to working in the linked PR, just have to deal with tabs and an edge case or two.
