### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by sander1095** [belav/csharpier#976]
I'm currently using .NET 8 RC2. When I try to install csharpier in my CI/CD pipeline on Azure Pipelines, I get the following error:

```
- script: |
    dotnet tool restore
    dotnet csharpier --check .
  displayName: "Lint Pull Request"
```

```
You must install or update .NET to run this application.

App: /home/vsts/.nuget/packages/csharpier/0.25.0/tools/net7.0/any/dotnet-csharpier.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: /opt/hostedtoolcache/dotnet/

The following frameworks were found:
  8.0.0-rc.2.23479.6 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]
```

Could support for RC2 be added? Or perhaps support for .NET 8 as soon as it is out?

**Comment by belav** [comment]
I am planning to add net8 support in the next release, which I should hopefully have out in the next week or two. In hindsight it  would have made sense to support net8 already, because I believe csharpier doesn't need to be updated after Net8 is official even if it was built with one of the preview or RC builds.

**Comment by sander1095** [comment]
@belav  I do think some changes are needed for C# 12 support.

I have a file that contains the following code:

```
        Func<Exception, IActionResult>[] handlers =
        [
            // You can add handlers for specific exceptions here.
            // Examples: Domain validation, unauthorized exceptions, etc...
        ] ;
```

This ` = []` is a new C# 12 concept. When I run `dotnet csharpier .`, I get the following error:

```
Warning <STUFF>/ErrorController.cs - Failed to compile so was not formatted.
  (27,52): error CS1525: Invalid expression term '['
  (28,10): error CS0443: Syntax error; value expected
```

**Comment by belav** [comment]
Yeah that was something I missed, or wasn't available when I added the initial c# 12 support. Support was added in #966 which will be in the next release.
