### ISSUE TITLE
EditorConfig hierarchy not working as expected

### ISSUE THREAD

**Issue by parched** [belav/csharpier#987]
In the root directory I have `.csharperrc.yaml` which specifies the line length as 120.
Also, in the root directory I have `.editorconfig` which doesn't specify the line length.
In subdirectory `A` I have an `.editorconfig` which doesn't specify the line length either. (Note it also does not have `root = true`)

When I run `dotnet csharpier .` in the root directory, all the files in `A` get formatted with line length `100` (the default).

I expected the line length in the root `.csharpierrc.yaml` to be used, but it only does this when the `A/.editorconfig` doesn't exist.

I've now added `max_line_length = 120` to the root `.editorconfig` and it works, but this was a surprise when upgrading to 0.26.

**Comment by belav** [comment]
The logic for this is currently

1. Starting from the directory for a given file being formatted
2. If the current directory contains a `.csharpierrc` use that
3. Else if the current directory contains a `.editorconfig` use that. Take into account any `.editorconfig` files in parent folders until `root = true` is found

I'm thinking there are two possible fixes.

1. If there is a `.csharpierrc` in or above the file being formatted, that will take priority over any `.editorconfig` file.
2. In the case where an `.editorconfig` is found, merge the settings from it with the first `.csharpierrc` file that is found above a given `.editorconfig`

The first option is definitely easier to implement and also a lot easier to understand how it works. It seems like the correct way to handle this.

**Comment by parched** [comment]
Option 1 sounds good to me.
