### ISSUE TITLE
Prevent line break when we have single line into a block. 

### ISSUE THREAD

**Issue by arashbahreini** [belav/csharpier#998]
Lets say I have below code 

`if (condition) return true `

Csharpier turn this line into 

```
if (condition) 
    return true
```
Is there any way or configuration that keep my IFs in a single line when they have single line?

**Comment by belav** [comment]
No, CSharpier is opinonated and does not provide options for the sytle of formatting. It follows [Prettier's Option Philosophy](https://prettier.io/docs/en/option-philosophy.html)
